### ISSUE TITLE
Downloading nginx without verification

### ISSUE THREAD

**Issue by rugk** [wireapp/wire-server#10]
Do you believe it is a good idea [to download nginx](https://github.com/wireapp/wire-server/blob/develop/services/nginz/Makefile#L76) over an (insecure) HTTP connection and compile it without any verification?
At least this is what I see there. No gpg verification…

At least switching to HTTPS is easy as the nginx site nowadays [uses HTTPS](https://nginx.org/download/). However, I'd better recommend you to use gpg.

**Comment by jschaul** [comment]
Thanks for bringing up this issue.
