### ISSUE TITLE
Gundeck Memory

### ISSUE THREAD

**Issue by limengyu1990** [wireapp/wire-server#1016]
**Describe the bug**
When I run the load test tool, the server has 2 cores and 8g of memory. When 800+ people send messages, the `gundeck` memory increases a lot, and the`otr/message` interface returns `http-status 499`.
Therefore, I tried to comment out the logic of `websocket/native push`, leaving only the logic of` querying `Redis` and persistent notifications`, and then running the program again, and observed that the memory of `gundeck` still increased. I doubt if there is a memory leak.

`[Push]` size is 99. There is only one client per user. The operation of `Redis` is a simple `hgetall`, which should be completed in a few milliseconds, and it will not consume so much memory.

**To Reproduce**
```
 ./dist/api-loadtest  --api-host=test  --api-port=8080 --conversations-total=20  --conversation-bots=50  --bot-messages=1  --report-dir=. --conversation-passive-bots=50  --message-length=10 --max-events=4000  --enable-asserts --users-file=user-2000.csv --parallel-requests=4 --ramp-step=1000000 --event-timeout=10 
```

**Expected behavior**
I hope I can run the test with normal sized memory because it's just a simple `redis hgetall` query.
I want to know where is taking up so much memory, can you help me? thanks.

**Screenshots**
### function param:  [Push] size is 99
![image](https://user-images.githubusercontent.com/8828406/76728912-e69a9d00-6792-11ea-87c9-95d1666c2e6c.png)
![image](https://user-images.githubusercontent.com/8828406/76729008-1b0e5900-6793-11ea-87b9-b3f360f3a047.png)
![image](https://user-images.githubusercontent.com/8828406/76728107-c4078480-6790-11ea-9204-4cce8eb66aef.png)
![image](https://user-images.githubusercontent.com/8828406/76728639-46dd0f00-6792-11ea-986d-513b0c4ee7c1.png)
### comment websocket/native logic
![image](https://user-images.githubusercontent.com/8828406/76727910-45124c00-6790-11ea-870b-854b4798d905.png)
![image](https://user-images.githubusercontent.com/8828406/76728619-2f058b00-6792-11ea-8c39-53281feefde1.png)
![image](https://user-images.githubusercontent.com/8828406/76728593-1ac18e00-6792-11ea-932a-7f8a34d39609.png)

**Additional context**
`services/gundeck/src/Gundeck/Push.hs`

`pushAll`

**Comment by fisx** [comment]
See also: https://github.com/wireapp/wire-server/issues/715

**Comment by fisx** [comment]
@limengyu1990 did you solve the issue?

**Comment by limengyu1990** [comment]
> @limengyu1990 did you solve the issue?

I plan to optimize it, such as: avoid `Redis`, `Cassandra` calls in a loop. then use c++ version Cassandra(https://github.com/scylladb/scylla);  and use `grpc` inside the service, and use Redis to cache more data,  try to optimize the `OTR/message` interface to less than 100ms under a large number of requests.

**Comment by fisx** [comment]
Thanks for sharing!

(Even though we haven't prioritized this up enough to take action yet, your input is really helpful.)

**Comment by jschaul** [comment]
@limengyu1990 we would be very happy to take code contributions on this (you could open a PR), if you have made improvements here.

**Comment by swamp-agr** [comment]
Please beware of Scylla: 
- It contains the bug: https://github.com/scylladb/scylla/issues/6307 incompatible with current server logic. 
- With scylla it would not be possible to pull latest data from `gundeck.notifications` scylla table.

**Comment by jschaul** [comment]
> Please beware of Scylla:
> 
>     * It contains the bug: [scylladb/scylla#6307](https://github.com/scylladb/scylla/issues/6307) incompatible with current server logic.
> 
>     * Grabbing whole bunch of notifications for specific user is also not good for server performance.
> 
>     * With scylla it would not be possible to pull latest data from `gundeck.notifications` table.

Thanks for this information!
