### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by perfectwebtech** [wireapp/wire-server#1038]
any additional step require for web socket deployment ?

**Comment by arianvp** [comment]
Websockets should work out of the box.

**Comment by perfectwebtech** [comment]
ssl redirect issue getting i using demo for product is it fine or using single machine  helm or kubernetes better ?

i am using demo docker one for production

as well swagger ui getting issue cross domain allow issue 
i did allowed in nginx conf file but even getting some problems 

else is there no auto installer shellscript all in one can install ?

i have all services compiled successfully but nginx conf file does not work well in  services base 

when i start services shell script then nginx conf they take somewhere else always dynamic changes

my changes does not effect in service bases 

but in demo mode work fine my changes but swagger url does not work

**Comment by arianvp** [comment]
for production environments we would advice the `helm` and `kubernetes` setup

The demo docker instance is mostly used for development; and is also not persistent.

> else is there no auto installer shellscript all in one can install ?

Installation instructions for Helm can be found here https://docs.wire.com
