### ISSUE TITLE
Getting error while installing team-settingst helm chart on k8s

### ISSUE THREAD

**Issue by devopsrajpurohit** [wireapp/wire-server#1093]
helm install wire/team-settings
Error: render error in "team-settings/templates/secret.yaml": template: team-settings/templates/secret.yaml:12:23: executing "team-settings/templates/secret.yaml" at <required "No .secrets found in configuration. Did you forget to helm <command> -f path/to/secrets.yaml ?" .Values.secrets>: error calling required: No .secrets found in configuration. Did you forget to helm <command> -f path/to/secrets.yaml ?

**Comment by akshaymankar** [comment]
Hi @devopsrajpurohit, this issue is also reported here: https://github.com/wireapp/wire-server-deploy/issues/258. Please let us know there if you have more questions.
