### ISSUE TITLE
Error loading shared library libssl.so.1.1

### ISSUE THREAD

**Issue by maybeTomorrow** [wireapp/wire-server#1107]
when i use docker to build alpine image,i got Error loading shared library libssl.so.1.1: No such file or directory (needed by /usr/bin/brig),,i got libssl.so.1.0 in /usr/lib
also 
Error loading shared library libicuuc.so.64: No such file or directory (needed by /usr/bin/brig)
brig         | Error loading shared library libicui18n.so.64: No such file or directory (needed by /usr/bin/brig)
brig         | Error loading shared library libicudata.so.64: No such file or directory (needed by /usr/bin/brig)

**Comment by lucendio** [comment]
Would you mind filling in the [template](https://github.com/wireapp/wire-server/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) that we have prepared for new issues?

**Comment by maybeTomorrow** [comment]
i resolved,docker image quay.io/wire/alpine-deps is too old from quay.io,i build it by local
