### ISSUE TITLE
Wire - Backup Conversations - Plain Text

### ISSUE THREAD

**Issue by ccao001** [wireapp/wire-server#1201]
* [ x] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**

Hi, 

It looks like the only way to see my backed up conversations is by importing the `Wire-ccao001-Backup_2020-09-03.desktop_wbu` file into another wire client.

I would like to get a plain text back up of all my conversations.

Is there currently a way to do that or are backups tied to the wire platform?

Thank you!

- Carla

**Comment by akshaymankar** [comment]
Hey @ccao001, 

From the wire-server perspective, it is impossible to serve content of the conversations as it is all end to end encrypted.
 
The clients **officially do not support** plain text exports. But there is a hack you can use. Of course we don't promise any guarantees of it working now or in the future. The `desktop_wbu` file is just a zip archive. If you just unzip it, you will find all the conversation data in some JSON files.

**Comment by arianvp** [comment]
@ccao001 here is a little script on the wire-desktop backups before to get them in a bit more useful output. It will group all the messages per conversation, and sort them by chronological time

```
unzip  <desktop_wbu file>
cat events.json | jq '. | group_by(.conversation) | map (sort_by(.time))' > events_per_conversation.json
```

**Comment by arianvp** [comment]
I hope the above helps you. I'm going to close this now; as backup formats and clients do not really have anything to do with the backend and thus is not actionable for us.  Feel free to leave additional questions here though.
