### ISSUE TITLE
k3 & docker-compose

### ISSUE THREAD

**Issue by dm17** [wireapp/wire-server#1262]
Seems like this is k8-based? Are there any plans or support for mere k3 or docker-compose support? I'd prefer not to run a whole k8, preferably...
Thanks!

**Comment by flokli** [comment]
The code is meant to run on Kubernetes. You should be able to also run it in a k3s cluster, if it has enough compute.

There's no plans to ship a docker-compose file, as the setup is quite complicated and maintaining two different stacks is a lot of work.
