### ISSUE TITLE
Using both self-hosted & public Wire?

### ISSUE THREAD

**Issue by dm17** [wireapp/wire-server#1284]
I don't know if I phrased this question correctly, but in terms of self hosting and adding various contacts. How can one know which contacts are chatting via our self-hosted server versus the public wire server(s)? Can they both be used? Perhaps I missed the documentation explaining this, but it could be a bit clearer...
Thanks!

**Comment by mheinzel** [comment]
Not 100% sure if I understood the question correctly, but at the moment each account exists on one server only (public or self-hosted) and can only communicate to other users on the same server. 
With federation, it will become possible to communicate across multiple servers, but until then you would need separate accounts to be able to talk to users registered on different servers.

Did that answer your question?

**Comment by dm17** [comment]
@mheinzel Thanks! Ya, good answer. So sounds you'd just have 1 account per wire server (self hosted or public in this case). And I suppose I'll realize how to direct my users to register their account on my server (instead of public) during setup.

**Comment by dm17** [comment]
By the way, federation sounds complex and I've not seen any company do it well yet. I hope wire figured out how to simplify it greatly :)

**Comment by mheinzel** [comment]
> I suppose I'll realize how to direct my users to register their account on my server (instead of public) during setup.

Yes. For the webapp that means directing the users to your own self-hosted webapp, for mobile clients you probably have seen [the page on deep links](https://docs.wire.com/how-to/associate/deeplink.html) already (although I'm not 100% sure how account creation through the app works in that case) and for the desktop client you can pass the deep link via `--env {URL}`.

I'll close this for now, feel free to re-open if you have related questions!
