### ISSUE TITLE
question on account migration

### ISSUE THREAD

**Issue by cz-michi** [wireapp/wire-server#145]
hello,

how will be account administrated?
if i register now account and then i would like to start own wire server, will there be a chance to migrate account to own server? or how will this be working?
how will be server2server working? i'm now running xmpp server and there are dns records to find correct server by domain.

maybe i'm missing something, but i'm looking forward to getting light into this :-)

**Comment by tiago-loureiro** [comment]
Hi @cz-michi, thanks for your interest! Unfortunately, there are no plans for the account migration as you describe it.

However, self hosting and federation are indeed the roadmap, but there are no exact dates to be shared at the moment. We can only ensure that we are currently working on the self hosting version and, as mentioned [here](https://github.com/wireapp/wire-server#wire-server) federation is also something we will start working on _at some point_.

Keep tuned with our updates on this repo and also https://medium.com/@wireapp/

**Comment by cz-michi** [comment]
thanks a lot
is there any way to support (donate) your hard work?

**Comment by strypey** [comment]
@ghost encourage any professional teams you know who can afford it to buy a license for the pro version of Wire.
