### ISSUE TITLE
Federated version of Wire

### ISSUE THREAD

**Issue by avently** [wireapp/wire-server#16]
I wrote this issue just for future. One day you will want to make federated version of Wire. That day will be added to history of the private communication. 
But for now maybe you want to track your progress or to ask people about their vision on Wire's federated version. 

I think you have good examples but not so private and anonymous as we want to have. So Wire will be first.

**Comment by david-wire** [comment]
Thanks for the note. 

As usual when we introduce new features and updates, we will make announcements on our channels:
https://medium.com/@wireapp and https://medium.com/@wireupdates.

**Comment by marcoconti83** [comment]
Hi @avently  , 
Thanks for getting in touch. 

Wire doesn't currently have a stand-alone server version that can be deployed on your own infrastructure. We have plans to make it available at some point, so please stay tuned.

**Comment by marcoconti83** [comment]
There is a similar issue opened here: https://github.com/wireapp/wire-server/issues/2

As it's easy to track this on a single issue, I will close this one as a duplicate. Please refer to the other issue for updates.

Thanks!
