### ISSUE TITLE
Why Haskell!

### ISSUE THREAD

**Issue by questionpython** [wireapp/wire-server#165]
Hello,

Question : Why choose `Haskell` for the server and API?
May you explain me with reasons?
Why not Nodejs+SocketIO/C/CPP/RUST?
  
  
  @tiago-loureiro

**Comment by fisx** [comment]
I was not involved in the decision, but I can give you lots of good reasons: Haskell is expressive and concise, fewer lines of code means fewer bugs.  The Haskell type system renders many programming errors impossible that you've seen in other languages, while it makes testing and refactoring so much easier it still surprises me after I've known the language for almost 20 years.  The ghc compiler and runtime are amazingly time and memory efficient.  It is easier to find and keep good developers if you let them work in Haskell.

You can find lots of material on this, from research papers on type theory to blog articles from people who are new to Haskell and want to share what they've learned.  Or this: http://baatz.io/posts/haskell-in-a-startup/.  Or go to gatherings near you and troll Haskellers in real life ;-).

You sound like you are frustrated, but you don't explain very well why.  Why do you want to discuss choice of language of a code base this mature?  What are your reasons against wire's choice and for your preferences?  What specifically did you hope to accomplish by opening this issue?

Anyway, I hope this answer inspires you!  (-:

**Comment by clqn** [comment]
Not a wire dev, just a fan of big Haskell (i'm not super great with it but i just really enjoy writing in it). I was pretty pleasantly surprised to see that it was being put to use in my favorite chat app! Nice choice, Wire. :3

**Comment by tiago-loureiro** [comment]
@questionpython Hope that @fisx has inspired you and helped clear some doubts :)

Will close down this issue for now, thank you for your interest!
