### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by FihlaTV** [wireapp/wire-server#168]
Hi 
I followed your instruction in building server with docker, but  I run into this error
error: Package `sodiumoxide v0.0.14` does not have these features: `std`  

Any help. Thanks

**Comment by jschaul** [comment]
Thanks for reporting. We upgraded the rust dependencies [here](https://github.com/wireapp/cryptobox-c/commit/b121b0dfdd42f5ac49cdbbc3bb3e1517d30d68d1) which should resolve this issue. Please re-open an issue if compilation problems remain.
