### ISSUE TITLE
Wire-server binaries

### ISSUE THREAD

**Issue by FihlaTV** [wireapp/wire-server#176]
Hi 
I have followed the build instructions and docker instructions. However I cannot see any binaries or any way on how to run wire server  or it's services. I see in make process wire server makes some diretories , but I cannot find them in wire source directory or /usr/bin either. Do we manually find a way top build binaries?
thanks

**Comment by stevemill2014** [comment]
wire-server/dist

**Comment by tiago-loureiro** [comment]
Hi @FihlaTV 

We have made a number of changes on our documentation and should be now far more straightforward to get things up & running.

As the previous user described, you can find all the generated binaries under `wire-server/dist` but we would really recommend going through https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md and seeing if you still encounter any problems starting the services.
