### ISSUE TITLE
wire-server installation

### ISSUE THREAD

**Issue by saidiahd** [wireapp/wire-server#194]
Hi folk,
For a wire-server installation, is it necessary to configure all the external components (SNS,S3 …)? 
Thanks

**Comment by jschaul** [comment]
Hi @saidiahd 

thanks for your interest in wire-server. Yes, at the moment it is necessary to have a AWS account and to configure all external components, such as SNS, SES, SQS, DynamoDB, cassandra, elasticsearch, redis, etc. We're aware of the related complexity, and we're currently working on both reducing this complexity and documenting necessary steps.

**Comment by c0fe** [comment]
There is no method of utilizing local components rather than having to use the external services?

**Comment by sd166** [comment]
Please tell me how to start the server for the test. Is there an AWS account where to make settings for the correct operation? Which branch to choose? Thank you in advance. On which OS to collect Ubuntu or Centos?
