### ISSUE TITLE
Is it possible to run on Google Cloud or any other platform

### ISSUE THREAD

**Issue by FihlaTV** [wireapp/wire-server#200]
I See the Wire-server is built using AWS configuration., Can it be ported to other cloud servers such as Google Cloud or any VPS

**Comment by jschaul** [comment]
Hi @FihlaTV 

thanks for your interest in wire-server. In a first phase, you will need an AWS account. At the moment it is necessary to have an AWS account and to configure all external components currently necessary, such as SNS, SES, SQS, DynamoDB, S3, cloudfront, etc. We're aware of the related complexity, and we're currently working on both reducing this complexity and documenting necessary steps. Eventually we might change our code in such a way to be able to operate independently from AWS, but this will take time.

**Comment by neongreen** [comment]
Closing this issue in favor of #2. Please subscribe to that issue to get a notification when it will be possible to deploy your own backend!
