### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by yangzhaofei** [wireapp/wire-server#221]
What containers are needed to run

**Comment by tiago-loureiro** [comment]
Hi @yangzhaofei 
Extensive documentation on how to run in a production mode is not fully ready yet but partially available [here](https://github.com/wireapp/wire-server#how-to-run-wire-server)

If you want to run some integration tests, [this](https://github.com/wireapp/wire-server#how-to-run-integration-tests) should get you going.

Will close this down for now, please (re)open if you have other concrete questions.
