### ISSUE TITLE
Error In Make

### ISSUE THREAD

**Issue by carryon** [wireapp/wire-server#225]
![image](https://user-images.githubusercontent.com/2255313/37015742-ea0e7692-2143-11e8-9649-a63d7a7b3bf7.png)

con$ cd build/alpine && make
docker build -t wireserver/alpine-deps:local -f Dockerfile.deps .
Sending build context to Docker daemon  20.99kB
Step 1/5 : FROM alpine:3.7 as cryptobox-builder
 ---> 3fd9065eaf02
Step 2/5 : RUN apk add --no-cache cargo libsodium-dev git &&     cd /tmp &&     git clone https://github.com/wireapp/cryptobox-c.git &&     cd cryptobox-c &&     cargo build --release
 ---> Running in 8116d19f8ab3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: BAD signature
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz: BAD signature
ERROR: unsatisfiable constraints:
  cargo (missing):
    required by: world[cargo]
  git (missing):
    required by: world[git]
  libsodium-dev (missing):
    required by: world[libsodium-dev]
The command '/bin/sh -c apk add --no-cache cargo libsodium-dev git &&     cd /tmp &&     git clone https://github.com/wireapp/cryptobox-c.git &&     cd cryptobox-c &&     cargo build --release' returned a non-zero code: 3
make: *** [deps] Error 3

**Comment by xixi647** [comment]
I have another problem when I run `make`, 
```
   Configuring cryptobox-haskell-0.1.1...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependency on a foreign
    library:
    * Missing C library: cryptobox
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
make: *** [install] Error 1
```

as a matter of fact, I did download the cryptobox and use `make` & `make dist` to generate a deb file and install it in my linux OS, but this error didn't gone, should I put the generated libcryptobox.so in a proper path ? where should I put? anyone can help on this?

**Comment by carryon** [comment]
I already solved it, just not close this issue.
My problem is that not install some packages, like gcc, bash, xz, llvm, icu4c etc.
