### ISSUE TITLE
unconfigured table meta

### ISSUE THREAD

**Issue by wssll789** [wireapp/wire-server#229]
service: Failed to read schema version from meta table. Error was: Invalid "unconfigured table meta"
CallStack (from HasCallStack):
  error, called at src/Cassandra/Schema.hs:99:11 in cassandra-util-0.16.5-AkzXtK0RA1x9xLYL98aoZu:Cassandra.Schema

@jschaul

**Comment by elverkilde** [comment]
@wssll789 you will need to run the schema executables before running the service executables. As an example, for the `brig` service you need to run the `brig-schema` executable first to set up the table.

**Comment by tiago-loureiro** [comment]
Hi @wssll789 

There is now a more thorough description of how to set all services up, please go through 
https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md and let us know if something is still unclear.
