### ISSUE TITLE
Warning when building docs

### ISSUE THREAD

**Issue by arthurwolf** [wireapp/wire-server#2299]
**Describe the bug**
Warning when building the docs from docs/ (after recent migration from wire-docs repo)

**To Reproduce**

* Git clone this repo, cd docs
* make docs
* Get this output:

╰─⠠⠵ make docs                             on  develop|✔
docker run --rm -v $(pwd):/mnt quay.io/wire/alpine-sphinx:0.0.111 make clean html
rm -rf "/mnt/build"
sphinx-build -M html "/mnt/src" "/mnt/build" -q
/nix/store/brp9dz5v47zxwkskffy57pzf8fmng2rm-python3-3.8.8-env/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))

**Expected behavior**
Shouldn't see a warning.

**Comment by stephen-smith** [comment]
Could be: https://github.com/readthedocs/recommonmark/issues/177 ?

**Comment by stephen-smith** [comment]
If so, we'd either have to stop using recommonmark (probably switching to myst_parser like our sphinx conf.py says) or patch recommonmark and use our own version.

The patch would be small, but probably not worth the maintenance trouble going forward.  So, we should see if we can switch to myst_parser.

**Comment by stephen-smith** [comment]
I guess we either need to get myst-parser in nixpkgs or maintain our own nix recipe for that.  https://github.com/lazyprop/haskell-language-server/blob/master/myst-parser.nix might work are a recipe but as far as I can tell nothing has landed in https://github.com/NixOS/nixpkgs yet.

**Comment by flokli** [comment]
Fixed by https://github.com/wireapp/wire-server/pull/2594, which moves markdown rendering to myst.
