### ISSUE TITLE
Where could I get the zauth module info?

### ISSUE THREAD

**Issue by TonyWuLihu** [wireapp/wire-server#239]
This is an awesome work for you team. I'm trying to get my foot wet and feel it.  However, after I build the nginz docker, I tried to bring it up a container, it failed with 
Starting nginx
2018/03/14 15:34:20 [emerg] 7#0: missing 'zauth_keystore' in /etc/nginx/nginx.conf:117
nginx: [emerg] missing 'zauth_keystore' in /etc/nginx/nginx.conf:117
I know it's related to the zauth config, but any reference or information I could get? Even no result with Google. 
Please, we are looking forward setup the infrastructure very soon.

**Comment by elverkilde** [comment]
Hi @TonyWuLihu, thank you for your interest in Wire.

nginz is used internally at Wire and is mainly used for authentication. If you wish to run Wire yourself, I would suggest you start with the main services; `brig`, `galley`, `gundeck` and `cannon`.

If you have a specific need for running nginz, let us know and we can try to assist with that specific use case.

**Comment by TonyWuLihu** [comment]
@elverkilde Thanks for your quick response!!! I love the architecture diagram very much!  nginz as proxy for external request, and this would minimize the exposed ports to outside world, and nginx could be easily scaled out. We have similar use case like this, I know zauth is developed by Wire internally, so if there is any example for setting up nginx with zauth module, that would be fantastic !

**Comment by TonyWuLihu** [comment]
mainly the nginx configuration

**Comment by tiago-loureiro** [comment]
Hi @TonyWuLihu 

You can have a look over our latest instructions [here](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md), which should make things clearer for you (includes a demo config for all services including nginz and the keystore).

Feel free to reopen if something is still not clear, thanks for the interest!
