### ISSUE TITLE
Why not swagger-ui

### ISSUE THREAD

**Issue by yangzhaofei** [wireapp/wire-server#253]
Why not swagger-ui

**Comment by yangzhaofei** [comment]
Is it not available

**Comment by tiago-loureiro** [comment]
hi @yangzhaofei 

If you follow the instructions [here](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md) you will see that you can access our API through swagger on  http://127.0.0.1:8080/swagger-ui

Feel free to reopen if something is still unclear or not functioning.
