### ISSUE TITLE
brig and galley have no place to config aws region

### ISSUE THREAD

**Issue by Cospotato** [wireapp/wire-server#256]
My AWS Service Region：
SQS service is in `us-east-2`
SES service is in `us-east-1`
dynamoDB is in `us-east-2`

When I starting the brig/galley service, I got this error message:
```
service: GeneralError (ServiceError (ServiceError' {_serviceAbbrev = Abbrev "SQS", _serviceStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, _serviceHeaders = [("Server","Server"),("Date","Sun, 25 Mar 2018 03:35:42 GMT"),("Content-Type","text/xml"),("Content-Length","322"),("Connection","close"),("x-amzn-RequestId","21de53ba-6909-52ba-b731-008b7247b060")], _serviceCode = ErrorCode "SignatureDoesNotMatch", _serviceMessage = Just (ErrorMessage "Credential should be scoped to a valid region, not 'us-east-1'. "), _serviceRequestId = Just (RequestId "21de53ba-6909-52ba-b731-008b7247b060")}))
```

**Comment by tiago-loureiro** [comment]
Hi @Cospotato 
`brig` and `galley` use amazonka as the AWS library, which in turn will try to load your AWS credentials in different ways as described [here](https://hackage.haskell.org/package/amazonka-1.5.0/docs/Network-AWS-Auth.html).

In our case, and when running our integration tests, we also need to set a default `AWS_REGION`, as shown and explained [here](https://github.com/wireapp/wire-server/blob/db9ce125b147030327afb1e8e50b0833e22c2f3b/services/integration.sh#L65-L67)

In your case, does `export AWS_REGION=us-east-1` help?
