### ISSUE TITLE
wire server installation issue

### ISSUE THREAD

**Issue by ogiright123** [wireapp/wire-server#264]
i am interesting in wire developement.
i built all components in wire server.
But i dont know how to run server.
can anyone give me full guide.
now Readme is not enough

**Comment by fisx** [comment]
Thanks for your interest in wire.  The README has only recently been polished, and it's good to see that the build process is now manageable for some people.  The README also says:

> How to run wire-server
> Documentation, configuration, and code for this is not ready yet (please do not open an issue to ask about this!).

If you have any particular questions that you would like to ask, please re-open this issue and give us more details.  This would be very helpful for us to write better documentation.  If you just want to have a full user manual: you have been heard!  We are doing our best to get this out as soon as possible.
