### ISSUE TITLE
How to configure the turn for voice/video?

### ISSUE THREAD

**Issue by nboooob** [wireapp/wire-server#267]
i used the restund server , but had a problem.
webrtc  call is ok, but ios app call is fail.
i watch the console output same string is "auth: unknown user 'd=1522688417.v=1.k=0.t=s.r=yafkhmsgnluzrhbf'"

brig.yaml
turn:
  servers: /etc/wire/turn/servers.txt
  secret: /etc/wire/turn/secret.txt

i tried some config for this file /etc/wire/turn/secret.txt(eg, username:HA1)  but it's incorrect.

thanks

**Comment by imanodaysoffdotcom** [comment]
@nboooob can you share your complete config to the wire server up and running. Maybe a video of how you setup the server and its components

**Comment by sd166** [comment]
I would also like to see a video on installing a wire-server

**Comment by tiago-loureiro** [comment]
Hello @Cospotato @sd166 @imanodaysoffdotcom @nboooob 

We are currently working on documentation on how to configure your TURN server. Please follow #127 to get updates on this topic
