### ISSUE TITLE
Add username mention notifications

### ISSUE THREAD

**Issue by WildYorkies** [wireapp/wire-server#268]
https://github.com/wireapp/wire-ios/issues/781

Scan message for `@username` or `@all` and notify users appropriately. This feature is very necessary for group conversations 

Ideally, we could also notify a user if one of their messages is replied to by another user. But replying to or quoting messages might be an additional issue

**Comment by jschaul** [comment]
As all message content is encrypted and therefore not readable by server-side code, your feature request is not in the right place on this repository. Feature requests can be sent via support: https://support.wire.com
