### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by weiganri** [wireapp/wire-server#27]
Is there any documentation that explains how to install the wire application on my own server?

**Comment by marcoconti83** [comment]
Hi @weiganri , 
Thanks for getting in touch. 

Wire doesn't currently have a stand-alone server version that can be deployed on your own infrastructure. We have plans to make it available at some point, so please stay tuned.

As usual when we introduce new features and updates, we will make announcements on our channels:
https://medium.com/@wireapp and https://medium.com/@wireupdates.

**Comment by marcoconti83** [comment]
There is a similar issue opened here: https://github.com/wireapp/wire-server/issues/2

As it's easy to track it on one issue, I will close this one as a duplicate. Please refer to the other issue for updates.

Thanks!

**Comment by Nemra1** [comment]
wire server doc website is down..any mirror pls?
