### ISSUE TITLE
Can I use localstack to mock AWS dependencies in standalone server installation?

### ISSUE THREAD

**Issue by eugenejen** [wireapp/wire-server#285]
Hi,

I am wondering is that possible to use [localstack](https://github.com/localstack/localstackl) to replace the AWS dependency in standalone server setup. Has anyone done it? If no, I will be interesting to give it a try. I know there are other external dependencies so the effort may not create a standalone installation on a local server.

**Comment by tiago-loureiro** [comment]
Hi @eugenejen 

Indeed, we have made that possible and you can have a look at our [docker-compose](https://github.com/wireapp/wire-server/blob/develop/deploy/docker-ephemeral/docker-compose.yaml) file.

We also have an open branch with a [README](https://github.com/wireapp/wire-server/blob/full-config/deploy/services-demo/README.md) that should get merged in during the coming days that will make it more clear how it all fits together.

**Comment by tiago-loureiro** [comment]
Hi again @eugenejen 

Said branch is now in develop (https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md) so please feel free to go through it and you should be able to start up a standalone installation. Let us know if something is still amiss.

**Comment by eugenejen** [comment]
thank you. i will check them out\
