### ISSUE TITLE
Setting user presence from 3rd party app

### ISSUE THREAD

**Issue by tompinzler** [wireapp/wire-server#286]
I‘m using Wire for a while now for my private communication whenever possible and I really like it. Great work guys!

I‘m currently looking for a self hosted chat server for my company. From what I understand it will be possible to run your own Wire server soon (dependencies on AWS are fine for us)

We need one (somewhat exotic) feature:
We need to be able to set the presence status of a user on the server from another application to busy and back to what it was before we set it to busy.

I read that user presence is end to end encrypted. While e2e encryption is one of the things that make Wire great I‘m worried that it is not possible to control presence of user from a 3rd party app.

My question in one sentence:

Will it be possible to set user presence via API or by editing the database to busy and back to what it was?

**Comment by elverkilde** [comment]
hi @tompinzler, as you correctly assume, this is not possible as the status is e2e encrypted, i.e. the server has no knowledge of or influence on the presences.

Only an authenticated client can modify its own status (the clients users' status) so I unfortunately don't see how this could be implemented (unless the 3rd party application (somehow) registers as an actual client of the user).

**Comment by tompinzler** [comment]
@elverkilde Thanks for confirming that!

I'm thinking about implementing an additional field to override the status set by the user. Whenever that field is set the client should show busy instead of the status set by the user.

It's probably a bigger project which requires modification of the server- and probably the client. I will have a look at the code and see what I can do.
