### ISSUE TITLE
Could you see all your messages from all your clients ? 

### ISSUE THREAD

**Issue by Twiggeh** [wireapp/wire-server#2909]
* [ x ] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**
Messages sent from a client is not available to the client after clearing IndexedDB.

Basically if you have  `userA´ with `clienta` and `clientaa` that sends a message to `userB` with `clientb` and `clientbb`. 

The message becomes, assuming we send from `userA` - `clientaa`

```
recipients: {
  "userA": {
      "clientaa": "encodedMSG",
      "clienta": "encodedMSG"
   },
   "userB": {
     "clientbb": "encodedMSG",
     "clientb": "encodedMSG"
   }
}
```
and the server returns a 201.

Now, if we switch to the device with `clienta`, we will see the sent message, even if we delete IndexedDB.
But if we delete IndexedDB on `clientaa` we will no longer see the sent message !

Is there a way to send the message so that one can see it from the same client ?

**Comment by jschaul** [comment]
The sending client receives an answer, if any, in the HTTP response payload. Its own payload is not persisted in the backend (you know the plaintext message you send at the time, it makes no sense to encrypt for yourself, persist in the backend, and re-download the message for your own client. Encryption sessions need two distinct client Ids AFAIK). The difference in observed behaviour between sending and receiving clients in the light of deleted IndexedDBs is to be expected. The backend filters out any client payloads if they are superfluous. If your example payload above included `userC: clientC` but this user isn't in the corresponding conversation, that user would not get a message. You can see this by inspecting the resulting HTTP response from your request (it gives feedback on deleted/unused/superfluous client payloads).

Functioning client functionality without message loss when manually wiping IndexedDB is not a feature Wire supports.

I hope that answers your question? If not, please re-open this or another issue with clarifying questions.
