### ISSUE TITLE
Wire server installation problem: debian, lubuntu

### ISSUE THREAD

**Issue by erotavlas85** [wireapp/wire-server#297]
Hi,
I'm trying to install the latest version of wire server under debian 9 64 bit, lubuntu 16.04 LTS 64 bit, ubuntu 16.04 LTS and 18.04 LTS both 64 bit.
I can successfully install the dependencies only under ubuntu while under debian and lubuntu I get the following error for cryptobox-c:
```
cargo build
   Compiling libsodium-sys v0.0.16
error: failed to run custom build command for `libsodium-sys v0.0.16`
process didn't exit successfully: `/home/clone/cryptobox-c/target/debug/build/libsodium-sys-33bf382dfdef1656/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Can you explain me why?
Moreover, the documentation is out of date since libssl-dev is required both under ubuntu family and debian.
Finally, the final command should be:
`git clone https://github.com/wireapp/wire-server && cd wire-server/tools/makedeb` instead of `git clone https://github.com/wire-server && cd wire-server/tools/makedeb`
Thank you

**Comment by fisx** [comment]
Thanks for the docs improvements; see #298.

I am not the right person to ask about the libsodium problem.  Can you set `RUST_BACKTRACE=1` and try again?

**Comment by neongreen** [comment]
@erotavlas85 ping

**Comment by erotavlas85** [comment]
@neongreen I'm sorry for the late reply. Yes, I confirm that with pkg-config installed it works in all the OS.
Now I will proceed by installing the wire-server.

**Comment by neongreen** [comment]
Your suggestions have already been merged in; for the `pkg-config` issue I just created a new PR.
