### ISSUE TITLE
bin and docs

### ISSUE THREAD

**Issue by 001101** [wireapp/wire-server#3]
**ARE MISSING**

**Comment by david-wire** [comment]
Yes, we are aware of that. This will be made available at some point, so please stay tuned.

**Comment by 001101** [comment]
in this stage it is nothing but some fragments from proprietary software

**Comment by marcoconti83** [comment]
Hi @001101 ,
Thanks for getting in touch. 

We are currently in the process of porting our services to this repository; it's an ongoing process.

Wire doesn't currently have a binary that can be deployed on your own infrastructure. We have plans to make it available at some point, so please stay tuned.

As usual when we introduce new features and updates, we will make announcements on our channels:
https://medium.com/@wireapp and https://medium.com/@wireupdates.

**Comment by marcoconti83** [comment]
There is a similar issue opened here: https://github.com/wireapp/wire-server/issues/2

As it's easy to track this on a single issue, I will close this one as a duplicate. Please refer to the other issue for updates.

Thanks!
