### ISSUE TITLE
can't find why demo.sh give the error 

### ISSUE THREAD

**Issue by jiamo** [wireapp/wire-server#306]
I already compile the source successfully. And run the `docker-compose up`.
While the demo.sh give the error
```
re-using existing TURN secret
re-using existing public/private keys
brig: user error (AesonException "Error in $: key \"cargohold\" not present")
[cargohold] I, Listening on 0.0.0.0:8084
``` 
I global search `AesonException` and don't find anything.

**Comment by tiago-loureiro** [comment]
Hi @jiamo, thanks for opening this issue.

Indeed after https://github.com/wireapp/wire-server/pull/296 we forgot to update the demo config for brig. It is now fixed after https://github.com/wireapp/wire-server/commit/6f0ef1f32a9834e145c284e3ca9978cf4caa869f;
please get the latest version our of code from the develop branch and that error will be gone.
