### ISSUE TITLE
mac os x make services can't work

### ISSUE THREAD

**Issue by jiamo** [wireapp/wire-server#308]
`make services` will make `nginz` while in mac os x
```
../third_party/nginx-zauth-module/zauth_module.c:6:10: fatal error: 'zauth.h' file not found
#include <zauth.h>
         ^~~~~~~~~
1 error generated.
```
So I will need install `libzauth`
```
➜  wire-server git:(develop) ✗ cd libs/libzauth
➜  libzauth git:(develop) ✗ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libzauth-c dist
cargo build --release
    Finished release [optimized] target(s) in 0.0 secs
mkdir -p deb/usr/local/include
mkdir -p deb/usr/local/lib/pkgconfig
cp src/zauth.h deb/usr/local/include/
sed -e "s~<<VERSION>>~"3.0.0"~" \
		-e "s~<<PREFIX>>~/usr/local~" \
		src/libzauth.pc > deb/usr/local/lib/pkgconfig/libzauth.pc
cp target/release/libzauth.dylib deb/usr/local/lib/
cp libzauth-c/target/release/*.deb .
cp: libzauth-c/target/release/*.deb: No such file or directory
make: *** [dist] Error 1
```
while I think in mac os x we don't need `deb` thing any more.

**Comment by tiago-loureiro** [comment]
> So I will need install libzauth

That's correct; dependencies needed for building nginz are shown [here](https://github.com/wireapp/wire-server/blob/1e548b4dba66beba8c45fcb383844ddb95139361/services/nginz/README.md#compile-natively)

> while I think in mac os x we don't need deb thing any more.

That's right, you don't actually need a debian package; however, the error you describe is actually not problematic, libzauth seems to have compiled properly for you; we will improve on this, @neongreen [is currently working](https://github.com/wireapp/wire-server/pull/305) on polishing this even further but after building/installing libzauth, you should be able to compile nginz.

**Comment by tiago-loureiro** [comment]
@jiamo Have you tried building `nginz` with the latest changes on our `develop` branch?

**Comment by jiamo** [comment]
Just have a try. success.
