### ISSUE TITLE
The problem with the demo: 403 Forbidden nginx

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-server#316]
I launch according to the instructions in [README.md](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md)

Displays in the console

```
root@ubuntu:~/wire-server/deploy/services-demo# ./demo.sh
Generate a secret for the TURN servers (must match the turn.secret key in brig's config)...
Generate private and public keys (used both by brig and nginz)...
[cannon] I, Listening on 127.0.0.1:8083
[brig] D, logger=cassandra.brig, connecting to 127.0.0.1:9042
[cargohold] I, Listening on 0.0.0.0:8084
[galley] I, logger=cassandra.galley, control connection: 127.0.0.1:9042#11
nginx: [alert] could not open error log file: open() "/var/log/nginz/error.log" failed (2: No such file or directory)
[gundeck] I, logger=cassandra.gundeck, control connection: 127.0.0.1:9042#11
[proxy] I, Listening on 0.0.0.0:8087
[brig] I, logger=cassandra.brig, control connection: 127.0.0.1:9042#11
[brig] I, logger=cassandra.brig, known hosts: [datacenter1:rack1:127.0.0.1:9042]
[brig] D, logger=cassandra.brig, client.connect=127.0.0.1:9042#12
[brig] I, Listening on 0.0.0.0:8082
[galley] I, logger=cassandra.galley, known hosts: [datacenter1:rack1:127.0.0.1:9042]
[galley] I, Listening on 127.0.0.1:8085
[gundeck] I, logger=cassandra.gundeck, known hosts: [datacenter1:rack1:127.0.0.1:9042]
[gundeck] I, Listening on 0.0.0.0:8086
All services up & running, Wire away!

```

I go to  http://127.0.0.1:8080/swagger-ui, it gives an error "403 Forbidden
nginx" in console "2018/05/11 06:14:22 [error] 116544#0: *9 open() "/root/wire-server/deploy/services-demo/conf/nginz/zwagger-ui" failed (13: Permission denied), client: 192.168.186.1, server: , request: "GET /swagger-ui HTTP/1.1", host: "192.168.186.140:8080""

**Comment by sd166** [comment]
The nginz.conf line was added to the file 
`user root`

But when I try to authorize, I get an error

![wire_app_swa](https://user-images.githubusercontent.com/10991740/39934733-6e2b18c4-554f-11e8-9d11-331013aab7c0.jpg)

**Comment by tiago-loureiro** [comment]
Hi @sd166 

Could you please try this again with our latest changes from develop?

> The nginz.conf line was added to the file
> user root

This change should not be necessary

**Comment by tiago-loureiro** [comment]
@sd166 
I will close this issue due to inactivity. Please feel free to reopen it if it still happens to you.
