### ISSUE TITLE
video chat bad error? web to web is not success! I use coturn server.

### ISSUE THREAD

**Issue by senlinms** [wireapp/wire-server#317]
4: handle_udp_packet: ------------------ xx ---------------- New UDP endpoint: local addr 103.45.21.47:4433, remote addr 125.84.184.192:3860
4: ****** session 003000000000000001: realm <> user <>: incoming packet BINDING processed, success
4: handle_udp_packet: ------------------ xx ---------------- New UDP endpoint: local addr 103.45.21.47:4433, remote addr 223.104.249.115:39145
4: ****** session 009000000000000001: realm <> user <>: incoming packet BINDING processed, success
4: ****** session 003000000000000001: realm <> user <>: incoming packet message processed, error 401: Unauthorized
4: ****** session 009000000000000001: realm <> user <>: incoming packet message processed, error 401: Unauthorized
4: check_stun_auth:**************************  find credentials Key of   HmacKey  
4: check_stun_auth:************************** Cannot find credentials of user <d=1526197552.v=1.k=0.t=s.r=nfihbmjmzkndxlcf>   HmacKey  
4: ****** session 003000000000000001: realm <> user <d=1526197552.v=1.k=0.t=s.r=nfihbmjmzkndxlcf>: incoming packet message processed, error 401: Unauthorized
4: check_stun_auth:**************************  find credentials Key of   HmacKey  
4: check_stun_auth:************************** Cannot find credentials of user <d=1526197552.v=1.k=0.t=s.r=nfihbmjmzkndxlcf>   HmacKey  
4: ****** session 009000000000000001: realm <> user <d=1526197552.v=1.k=0.t=s.r=nfihbmjmzkndxlcf>: incoming packet message processed, error 401: Unauthorized

f

**Comment by carryon** [comment]
@fisx @tiago-loureiro @neongreen @jschaul

**Comment by tiago-loureiro** [comment]
Hi @senlinms @carryon 

We are currently working on documentation on how to configure your TURN server. Please follow https://github.com/wireapp/wire-server/issues/127 to get updates on this topic
