### ISSUE TITLE
user can not sign up or login

### ISSUE THREAD

**Issue by mjheidari** [wireapp/wire-server#318]
hi.
i installed wire-server on my server,and custom wire-webapp to worked with my server.but in auth page in web app user can not sign up or login,and then this error occurred in server:
```
D, logger=aws.brig, [ServiceError] {
service = SES
status = 403 Forbidden
code = InvalidClientTokenId
...
```

**Comment by neongreen** [comment]
@mjheidari Did Tiago's suggestion work out for you? Please re-open the issue if it didn't.
