### ISSUE TITLE
this source and your server is not same

### ISSUE THREAD

**Issue by mjheidari** [wireapp/wire-server#324]
I run this server,but there are differents to your server.
1. GET /properties in this source return 404 not found,But in your server return an array
2. Send SMS or Email  not work in this(when send json object to /activate/send return error that "not a valid json value"). also in login

**Comment by mjheidari** [comment]
i set twilio/nexmo credentials , and run 
`curl -i -XPOST http://localhost:8082/login/send -H 'Content-type: application/json' -d '{"phone":"+1xxx"}'`
but brig error:
`ParseError "Error in $: Failed reading: not a valid json value"`

**Comment by fisx** [comment]
(Just to rule that out: I assume the phone number you actually sent consistet of more digits and fewer `x`, and you just edited this out for privacy?)

**Comment by mjheidari** [comment]
my phone number is correct and verified by twilio and nexmo, i post xxx for privacy. if phone number is not correct error: not E 164 format

**Comment by mjheidari** [comment]
i used fake aws,but my sms number and twilio/nexmo credentials are correct and valid.i run `demo.sh` and get  `All services up & running,Wire away!` ,also use and config webapp to connect to my own server and i can login with email(created by `create_test_user.sh`) and features works.but SMS login not work ( error 500 on webapp and `not a valid json value` by brig on server ). i can send my server's IP and user for you to test this.

**Comment by neongreen** [comment]
Closing because it's an old issue and it's unclear how to reproduce it; if the problem with SMS still persists, please open a new one.

**Comment by neongreen** [comment]
Oh btw, for everybody getting "Failed reading: not a valid json value" with curl: try adding `--trace-ascii /dev/stdout` to the curl invocation and check that your shell hasn't messed up.
