### ISSUE TITLE
Error when running fake aws

### ISSUE THREAD

**Issue by FihlaTV** [wireapp/wire-server#326]
Hi 
I am trying to run Wire-server with fake-aws according to all instructions in README pag4e, but I always get stuck on this elasticsearch error:
brig-index: HttpExceptionRequest Request {
db_migrations_1    |   host                 = "elasticsearch"
db_migrations_1    |   port                 = 9200
db_migrations_1    |   secure               = False
db_migrations_1    |   requestHeaders       = [("Content-Type","application/json")]
db_migrations_1    |   path                 = "/directory_test"
db_migrations_1    |   queryString          = ""
db_migrations_1    |   method               = "HEAD"
db_migrations_1    |   proxy                = Nothing
db_migrations_1    |   rawBody              = False
db_migrations_1    |   redirectCount        = 10
db_migrations_1    |   responseTimeout      = ResponseTimeoutDefault
db_migrations_1    |   requestVersion       = HTTP/1.1

ConnectionFailure Network.Socket.getAddrInfo: does not exist (Name does not resolve))
db_migrations_1    | service not ready yet

**Comment by mjheidari** [comment]
Unfortunately, there are a lot of bugs in this project, but nobody is accountable.

**Comment by jschaul** [comment]
@FihlaTV it looks like when you run `deploy/docker-ephemeral/run.sh`, which should start (among other things) elasticsearch on port 9200. The error you're getting indicates that this does not happen for you. 
Possible reasons could be that your machine doesn't have enough RAM, or docker is in a strange state. Perhaps you could try, after running  `deploy/docker-ephemeral/run.sh`, in a separate terminal, `cd deploy/docker-ephemeral`, then `docker-compose ps`. If all works out, it should print something like the following:

```
              Name                             Command               State                    Ports                
-------------------------------------------------------------------------------------------------------------------
dockerephemeral_aws_cli_1           /scripts/init.sh                 Exit 0                                        
dockerephemeral_cassandra_1         docker-entrypoint.sh cassa ...   Up       7000/tcp, 7001/tcp, 7199/tcp,        
                                                                              0.0.0.0:9042->9042/tcp, 9160/tcp     
dockerephemeral_db_migrations_1     /usr/bin/dumb-init -- /scr ...   Exit 0                                        
dockerephemeral_elasticsearch_1     /docker-entrypoint.sh elas ...   Up       0.0.0.0:9200->9200/tcp,              
                                                                              0.0.0.0:9300->9300/tcp               
dockerephemeral_fake_dynamodb_1     /docker-entrypoint.sh --sh ...   Up       0.0.0.0:4567->8000/tcp               
dockerephemeral_fake_localstack_1   /usr/bin/supervisord -c /e ...   Up       4567/tcp, 4568/tcp, 4569/tcp,        
                                                                              4570/tcp, 4571/tcp, 4572/tcp,        
                                                                              4573/tcp, 4574/tcp,                  
                                                                              0.0.0.0:4575->4575/tcp, 4576/tcp,    
                                                                              4577/tcp, 4578/tcp,                  
                                                                              0.0.0.0:4569->4579/tcp, 4580/tcp,    
                                                                              4581/tcp, 4582/tcp, 4583/tcp,        
                                                                              8080/tcp                             
dockerephemeral_fake_s3_1           /usr/bin/docker-entrypoint ...   Up       0.0.0.0:4570->9000/tcp               
dockerephemeral_fake_sqs_1          tini -g -- gosu ruby:ruby  ...   Up       0.0.0.0:4568->4568/tcp               
dockerephemeral_redis_1             docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp
```

`migrations`, `aws_cli` should have exited, all other things should be `Up`. If not, and say `elasticsearch` is shown in a different state than `Up`, you could try `docker-compose restart elasticsearch` or `docker-compose kill elasticsearch` followed by `docker-compose start elasticsearch`. `docker-compose -h` may give more options to look at.

@mjheidari Please note that any documentation on self-hosting, or how-to-run-wire-server-on-your-laptop is a work-in-progress and not (yet) officially supported by Wire. This means that bugs are expected, and we welcome issues and bug reports. Until it is officially supported, there is no dedicated support (i.e. responsible person) for these issues, however.

**Comment by neongreen** [comment]
> Please note that any documentation on self-hosting, or how-to-run-wire-server-on-your-laptop is a work-in-progress and not (yet) officially supported by Wire.

NB. If you want to be notified about the progress of that, please subscribe to #2.

**Comment by neongreen** [comment]
@FihlaTV feel free to ping me if the issue persists and you were unable to debug it.

**Comment by king6cong** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/302560/46844601-66883f00-ce0a-11e8-9c5a-ebf7bde2a520.png">

Docker-for-mac defaults to 2G memory usage, silimiar on other platforms. With cassandra and elasticsearch both being memory hungry, the 2G defaults will cause lots of memory thrashing, and  cassandra and elasticsearch can't be brought up simultaneously. With docker memory limits tuned up, in my case, 16G (not necessary that much, after everything brought up, RES mem usage is less than 2G), everything works fine.
