### ISSUE TITLE
Error connect to wire-server

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-server#343]
Started, when I try to authorize, I get an error. In the twillio and nexmo files are indicated the SID and API key

![wirewebapp](https://user-images.githubusercontent.com/10991740/40486174-3364034e-5f69-11e8-95d5-7d12c1762205.jpg)
what to do? what is the problem?

and console 
`[nginz] 192.168.186.1 - - [24/May/2018:05:37:51 -0700] "POST /login/send HTTP/1.1" 400 98 "http://192.168.186.140:8888/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-" - 5 0.604 0.604 - - - 4028c12b125e0785f1c4af81b77dadfe
[brig] D, code=400, label=invalid-phone, request=4028c12b125e0785f1c4af81b77dadfe, "Invalid mobile phone number."
`

**Comment by neongreen** [comment]
The `999` area code doesn't exist in Russia, and Twilio is smart enough to detect it. Try with a real phone number and ping us again if it doesn't work.

**Comment by sd166** [comment]
@neongreen  
In Russia there is a code 999 it uses Megafon. But also I use the real phone number which starts at 926 error also.

**Comment by neongreen** [comment]
Closing because it's an old issue and webapp might have gotten better in the meantime 🙂 Please try to reproduce and if the problem still exists, open a new issue.
