### ISSUE TITLE
Error Webapp + wire-server

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-server#347]
It was authorized on the local computer where the webapp is launched.
at **http://localhost:8088/app**

in the browser console produces an error, seen in the screenshot.

![webapp_error_console](https://user-images.githubusercontent.com/10991740/40501295-1f67610c-5f90-11e8-88b3-4847ee4a43b6.jpg)

**Comment by neongreen** [comment]
@sd166 can you please either close the issue or confirm that it's still relevant for you? (I'm cleaning up stale issues)

**Comment by sd166** [comment]
The problem is not solved! But I could not repeat it. I'm closing the issues for now
