### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by phasium** [wireapp/wire-server#352]
when trying to install makedeb
```
AesonException "Invalid flag name: \"bytestring--lt-0_10_4\""
Makefile:25: recipe for target 'clean' failed

```

**Comment by neongreen** [comment]
What version of Stack do you have? Afaik recent versions of Stack have a
workaround for it.

**Comment by phasium** [comment]
The latest one.

**Comment by neongreen** [comment]
Okay, that's weird. I'm not sure what to do here, to be honest. Everything that I know suggests that it should be fixed (e.g. see https://github.com/commercialhaskell/stackage/issues/2759). Are you 100% sure that you don't have e.g. two versions of Stack and the one on PATH is older? (Often people would have Stack installed globally and also in ~/.local/bin, for instance)

**Comment by jschaul** [comment]
What is your `stack --version`? `latest` is not a version number.

**Comment by phasium** [comment]
Seems to be fixed, reinstalled.
