### ISSUE TITLE
Building wire-server locally 

### ISSUE THREAD

**Issue by P1ro** [wireapp/wire-server#3696]
Building wire-server locally

## Context:

> when trying to build with make or cabal build all I'm getting:
Error: cabal: Failed to build wire-message-proto-lens-0.1.0 (which is required by test:wire-api-tests from wire-api-0.1.0, test:wire-api-golden-tests from wire-api-0.1.0 and others).

Did install nix package manager direnv and add nix cache, had to enter nix folder inside wire-server.

### How did you install wire-server?

> manually compiling

### How many servers are involved?
1

Linux monster 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by akshaymankar** [comment]
Did you clone the submodules?

**Comment by P1ro** [comment]
> Did you clone the submodules?

Im following this one, [https://github.com/wireapp/wire-server/blob/develop/docs/src/developer/developer/building.md](url) what do you mean with clone the submodules?

**Comment by akshaymankar** [comment]
When you clone wire-server, you need to clone it with `--recursive`. If it is already cloned, run this to get all the git submodules: `git submodule update --init --recursive`

**Comment by P1ro** [comment]
> When you clone wire-server, you need to clone it with `--recursive`. If it is already cloned, run this to get all the git submodules: `git submodule update --init --recursive`

Thanks, that was it, didn't knew about it.

**Comment by P1ro** [comment]
Sorry for bother with this again, why I might be getting:
run-services: Network.Socket.connect: <socket: 39>: does not exist (Connection refused)
when I try to run-services
