### ISSUE TITLE
error in login/send

### ISSUE THREAD

**Issue by joomlaroad** [wireapp/wire-server#379]
![sw](https://user-images.githubusercontent.com/40336074/41507851-262c2842-7250-11e8-90e0-0db6a5e86451.jpg)
![server](https://user-images.githubusercontent.com/40336074/41507854-26df5bec-7250-11e8-812a-ab7761b41bfc.jpg)

**Comment by fisx** [comment]
I can't find anything wrong with the input you show there.  Moreover, this is the error message you get e.g. if you forget a closing `}` as opposed to forget to include some required fields in the object.

Strange!  My first shot in the dark would be "perhaps something in your setup tried to escape the quotes to make it valid HTML?"  But I'm most likely miles off.

What client software are you using?  Do you have a way to log the HTTP traffic before it hits wire-server, to make sure your request looks like what you would expect?

**Comment by joomlaroad** [comment]
> What client software are you using?

Firefox & Chrome & cURL

> Do you have a way to log the HTTP traffic before it hits wire-server, to make sure your request looks like what you would expect?

it's Ok.

**Comment by mjheidari** [comment]
I also have this problem. on '/login/send/' and '/activate/send'(if use phone instead of email)

**Comment by neongreen** [comment]
Can you please send the exact curl invocation so that I could try to replicate it locally?

**Comment by jschaul** [comment]
I'm not sure if it's directly related to the error you're getting (But the 500 indicates that it's perhaps a problem with configuration parsing, not with the actual request body); but for using twilio, [this config line](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/conf/brig.demo.yaml#L39) has to be set.

**Comment by JiangJiabao** [comment]
Happy New Year

hello.
My name is jiabao.
I am very interested in wire-server.
I tried  to setup wire-server on my computer and I used the source code in https://github.com/wireapp/wire-server.
But I didn't setup.
If you have experienced in wire-server,
   Could you lend me a  hand?
I will wait for your reply.

My email address -  jiabao216@gmail.com

Thank you
Regards.
Jiabao.

**Comment by neongreen** [comment]
I'm getting:

```json
{
  "code": 403,
  "message": "Unauthorized e-mail address or phone number.",
  "label": "unauthorized"
}
```

There can be many reasons for that happening, including weird stuff like "macOS replaced quotes with curly quotes and nobody noticed" (for example).

If you reopen this issue, please post a cURL invocation that I can copy and paste.
