### ISSUE TITLE
[Privacy]Will metadata collected by privately-hosted Wire server shared to other servers?

### ISSUE THREAD

**Issue by voilaviola** [wireapp/wire-server#424]
Hello,
I would like to deploy Wire on our private cloud, and I wonder if the Wire metadata (user ID, connection list hash, etc) stored on cloud server will be shared with other Wire server or not? In our use case, we would like to keep all metadata locally.
Thank you in advance

**Comment by raphaelrobert** [comment]
Hi,
Wire does not yet support federation, which means there is no connection between Wire backend instances.

**Comment by voilaviola** [comment]
Thank you for your response!
