### ISSUE TITLE
Running restund docker

### ISSUE THREAD

**Issue by JimmyTinsley** [wireapp/wire-server#425]
Hello there,

After you guys released some documents about building turn server [here](https://github.com/wireapp/wire-server/pull/419), I successfully built and ran the restund service following the instruction [HERE](https://github.com/wireapp/wire-server/blob/develop/services/restund/README.md#building) by running `make build DOCKER=false` . `make build` also worked well and I've already got the `wire.com/restund            0.4.13w6b0 ` docker image, but when I tried to run this docker, I got the error:

> error loading configuration: /usr/local/etc/restund/restund.conf: No such file or directory

Could you please tell me where should I put the `.conf` file in? Thanks very much!

**Comment by tiago-loureiro** [comment]
You need to supply the `.conf` in the manner that is most convenient to you that docker can access. For instance, assuming you want to share a folder on your _local_ machine which contains the config at `/users/jimmy/restund/restund.conf`, then you could start `docker` like this:

```
docker run --network=host -v/users/jimmy/restund:/usr/local/etc/restund wire.com/restund:0.4.13w6b0
```

which should yield an output similar to:
```
turn: using public address w.x.y.z
zrest: selftest passed (pass=........==)
stun server ready
```

**Comment by JimmyTinsley** [comment]
Thank you a lot. That works perfectly well!

**Comment by kvaps** [comment]
Hey, I was also fighting with running restund on EKS, here is a short note:
https://medium.com/p/f69b9d8fa521/edit

**Comment by jschaul** [comment]
Thanks for the information @kvaps!
