### ISSUE TITLE
How to config virtual host in nginz?

### ISSUE THREAD

**Issue by o-u-p** [wireapp/wire-server#438]
So, when I use nginx, I can find a solution to add virtual host like https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04 , but it seems different to use nginz, because I tried to create /etc/nginx/sites-enabled, it failed, so is it possible to add virtual host to nginz? Any help will be appreciated :)

**Comment by JiangJiabao** [comment]
Happy New Year

hello.
My name is jiabao.
I am very interested in wire-server.
I tried  to setup wire-server on my computer and I used the source code in https://github.com/wireapp/wire-server.
But I didn't setup.
If you have experienced in wire-server,
   Could you lend me a  hand?
I will wait for your reply.

My email address -  jiabao216@gmail.com

Thank you
Regards.
Jiabao.

**Comment by julialongtin** [comment]
@o-u-p My apologies for not getting to your question earlier. Nginz is indeed mostly like nginx, but due to the time that has passed since your request, I'm going to close this issue, as i hope you've figgured it out. Feel free to open a new issue if you continue to have trouble.
