### ISSUE TITLE
Getting is error on setting up wire-server on local

### ISSUE THREAD

**Issue by cisrakesh** [wireapp/wire-server#447]
I am trying to install wire server on my ubuntu 16.04 , and when in run command 
deploy/docker-ephemeral/run.sh
i am getting following error.

db_migrations_1    | D, connecting to 172.18.0.3:9042
db_migrations_1    | I, control connection: 172.18.0.3:9042#3
db_migrations_1    | I, known hosts: [datacenter1:rack1:172.18.0.3:9042]
db_migrations_1    | D, client.connect=172.18.0.3:9042#4
db_migrations_1    | I, New migrations found.
db_migrations_1    | I, [35] Add service provider tables
db_migrations_1    | brig-schema: Invalid "Invalid column name provider because it conflicts with an existing column"
db_migrations_1    | service not ready yet
db_migrations_1    | Config file at /etc/wire/brig/conf/brig-schema.yaml does not exist, falling back to command-line arguments.

**Comment by neongreen** [comment]
@cisrakesh please ping if the issue is still relevant for you.
