### ISSUE TITLE
Security vulnerability about password reset

### ISSUE THREAD

**Issue by coercible** [wireapp/wire-server#465]
Currently when resetting password, we do `revokeAllCookies` in `/password-reset/complete` to logout all active clients. `revokeAllCookies` will delete cookies of the user from cassandra database.

The cookies are removed from cassandra, but the nginz doesn't know that. In the following several minutes after resetting password, **before the clients renew the cookie**, the active client still could do operations with old access tokens, such as sending message and removing clients. That would lead to security concern.

Is there any approach to tell nginz to forget all access tokens of specific user?

**Comment by coercible** [comment]
Any comment on this issue ?

/cc @tiago-loureiro

**Comment by tiago-loureiro** [comment]
Hi @coercible,

Your assessment regarding the validity of the access token is correct; this is a known tradeoff when using self encoded access tokens similarly for OAuth2.

A few ideas on improving this could be to have shorter access token lifetimes (at the expense of more network requests) or potentially rotating keys on brig/nginz, which would invalid ALL access tokens generated from that specific private key, forcing many users to renew their access tokens (quite impractical as you can see).

In the following several minutes after resetting password, before the clients renew the cookie, the active client still could do operations with old access tokens, such as sending message and removing clients. That would lead to security concern.

Adding/removing devices to/from your account requires your password; if you suspect that some device is/was compromised, you can decide which devices you want to keep in your account and which ones to eliminate which would make it impossible for someone else to use an access token to send any messages.

Given that the user that has just reset the password has control over the account and that the device management requires your password, the potential attacker would not be able to remove neither add any devices thus making it impossible to both send messages (you need a device on your account for that) and remove any clients.

(In addition, users can also verify devices to ensure that adding any device causes conversations to become unverified)

**Comment by coercible** [comment]
Thanks for the excellent explanation!
