### ISSUE TITLE
Update startup instructions Wire-server

### ISSUE THREAD

**Issue by sd166** [wireapp/wire-server#472]
Good afternoon!
Please update the instructions for launching the server part using the combat AWS. Also, the possibility of using a wire-webapp

**Comment by jschaul** [comment]
> combat AWS

I do not understand your question. What are you missing?

For wire-webapp related questions, please see https://github.com/wireapp/wire-webapp/.

**Comment by sd166** [comment]
How to configure the server with a public AWS, not fake AWS.
About Web. There is used  /self/consent but it is not in the server part

**Comment by JiangJiabao** [comment]
hello.
My name is Jiabao.
Today I read the wire-server.
I am very interested in wire-server.
So I tried to setup wire-server on my computer by using the https://github.com/wireapp/wire-server.
But I didn't setup.
Could you lend me a hand?
I will waiting for your reply.
Regards.
Jiabao

**Comment by neongreen** [comment]
@JiangJiabao Next time please open a new issue with a _specific_ issue that you've encountered (we can't help you if the only thing we know is "I didn't setup").

Do not spam in all open issues. If you do it again, I will restrict you from posting in this repo.

**Comment by neongreen** [comment]
I'm closing this issue in favor of https://github.com/wireapp/wire-server/issues/2 (please subscribe to it if you want to get news on self-hosting).
