### ISSUE TITLE
404 Not Found: GET /calls/config/v2

### ISSUE THREAD

**Issue by GiovanniMounir** [wireapp/wire-server#484]
I was able to run wire-server alongside wire-webapp on a self hosted Linux server, but calls/video is not working unfortunately. Exchanging messages and sharing images/S3 seem to be working properly.

I'm getting the following error in the demo.sh console from nginz whenever I try to call/video chat:

`[error] 28984#0: *1 open() "/home/ubuntu/wire-server/deploy/services-demo/html/calls/config/v2" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /calls/config/v2?_=1539045289881 HTTP/1.1", host: "website.com", referrer: "https://website.com/"`

Here is a screenshot of the Console logs from the browser (domain censored): https://i.imgur.com/JrlvRHW.png

wire-server is hosted at /restservice through a proxy.

I'm running Wire with fake dependencies and I followed the docs [here](https://github.com/wireapp/wire-server/blob/develop/doc/Dependencies.md) and [here](https://github.com/wireapp/wire-server/blob/develop/README.md). Did I miss something?

Thanks in advance!

**Comment by GiovanniMounir** [comment]
I was able to get video calls working by forwarding /calls to brig based on [this commit](https://github.com/wireapp/wire-server/pull/38/commits/8dfe31aa7ab101f45b7f83cf1e1a459c8af61a8b) - here is the nginx.conf section:

`location /calls/config
{
  include common_response_no_zauth.conf;
  proxy_pass http://brig;
}`

I'm not sure if the section was missing or if this is not the correct approach; any pointer will be greatly appreciated. Thanks!

**Comment by tiago-loureiro** [comment]
Hi @GiovanniMounir thanks for opening this issue. Indeed there was a missing route on our demo setup, it's now fixed with https://github.com/wireapp/wire-server/commit/3bbd9f27683601acbbc8293ab64f4ca97cfc6b37
