### ISSUE TITLE
SMS verification code consistently failing to country code +47

### ISSUE THREAD

**Issue by torlarse** [wireapp/wire-server#504]
I have tried to recruit 3 individuals to try Wire. One attempt on web login, two attempts on Android app. Trying to log in with phone number resulted in no SMS received. Country code +47 for all candidates.

Registration by mail was done from the web app for one candidate, but I did not push mail login for the candidates using their phones. 

I sent a mail to Wire support a while ago. No response as far as I can tell.

**Comment by neongreen** [comment]
@torlarse Are you still getting no SMS on +47 phones? If the issue persists I'll look into it.

**Comment by torlarse** [comment]
sms seem to be ok now, at least for one number

**Comment by julialongtin** [comment]
Closing issue, as it appears to have been resolved.
