### ISSUE TITLE
`makedeb` command Not Found

### ISSUE THREAD

**Issue by shinexia** [wireapp/wire-server#53]
thanks for your selfless sharing. I'm learning haskell and find this project. when i tried to install makedeb, i found the link https://github.com/twittner/makedeb is no longer exists, is there another place could get it?

**Comment by jschaul** [comment]
The `makedeb` project can be found under `tools/makedeb` in this same repository: https://github.com/wireapp/wire-server/tree/develop/tools/makedeb - note that you only need this in case you wish to create debian packages.

Out of curiosity, where did you find the (now outdated) link https://github.com/twittner/makedeb, so we can potentially update it?

**Comment by shinexia** [comment]
thx, the link is : https://github.com/wireapp/cryptobox-c#Package

**Comment by jschaul** [comment]
Thanks, the README of cryptobox-c has been updated.

**Comment by xixi647** [comment]
I have another problem when I run `make`, 
```
   Configuring cryptobox-haskell-0.1.1...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependency on a foreign
    library:
    * Missing C library: cryptobox
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
make: *** [install] Error 1
```

as a matter of fact, I did download the `cryptobox-c` and use `make` & `make dist` to generate a deb file and install it in my linux OS, but this error didn't gone, should I put the generated `libcryptobox.so` in a proper path ? where should I put? anyone can help on this?
