### ISSUE TITLE
Make server respond to websocket ping messages

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-server#560]
Webapp sends `'Wire is so much nicer with internet!'` [every now and then](https://github.com/wireapp/wire-webapp/blob/b6117ed93297feaab2ea845095d75a678161cfc4/app/script/event/WebSocketService.js#L224) to make sure it is still able to talk to the server. However because server doesn't respond to this message, in some cases it is impossible to detect if webapp is actually offline.

See this message for details: https://github.com/wireapp/wire-desktop/issues/1129#issuecomment-437965302

Please make Wire respond with some string like `'Indeed it is'` on each such ping request, so that it's possible to improve webapp.

**Comment by tiago-loureiro** [comment]
Hi @maximbaz 

Websockets have a built-in mechanism for this using [control frames](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Pings_and_Pongs_The_Heartbeat_of_WebSockets) which is already supported on the backend (check [this](https://github.com/wireapp/wire-server/blob/3b0b0812ee1e9cf3647bbd363b9515a6a9199262/services/cannon/src/Cannon/App.hs#L106-L122 ))

@bennyn Perhaps you want to have a look at this?

**Comment by maximbaz** [comment]
Hey hey @tiago-loureiro 👋 

Yes I know about those, unfortunately they are not supported by client-side javascript, that's the reason webapp is faking ping requests by sending strings to the server.

https://www.w3.org/TR/websockets/#ping-and-pong-frames

> The WebSocket protocol specification defines Ping and Pong frames that can be used for keep-alive, heart-beats, network status probing, latency instrumentation, and so forth. These are not currently exposed in the API.

**Comment by fisx** [comment]
Working on it.  Thanks @maximbaz for reporting this, and for not letting go!  :-)

**Comment by fisx** [comment]
I just talked with @bennyn:

- yes, the browser gives js no chance of learning about the death of its websocket other than the payload-level ping/pong game.
- we don't want to use protobuf to implement this like with all the other websocket traffic.  the backend dislikes the beaurocracy involved, and the web client would have to pay a performance penalty.
- instead, the message payloads are `ping` and `pong` (those 4 bytes).
- all messages other than `ping` sent by the client will be ignored as before.  this guarantees backwards compatibility (currently, the web client never sends `ping`).
- this plan needs to be confirmed by the other clients.

**Comment by maximbaz** [comment]
Solid plan 👍 Thank you both!

**Comment by marcoconti83** [comment]
To my understanding, this is an optional addition to the protocol. Only if a client sends a `ping`, the backend will respond with a `pong`. Currently no clients sends a `ping` so this addition is safe for older clients.

**Comment by maximbaz** [comment]
Yay for getting this merged! 🙂 @bennyn ping me if you want an early testing, or even for implementation if you guys are busy with other stuff, this is my most annoying issue with Wire on Desktop so I would be more than happy to collaborate again and get this implemented quickly 😉

**Comment by bennyn** [comment]
@maximbaz PRs are more than welcome because we won't have time this month to implement it ourselves.

**Comment by fisx** [comment]
@maximbaz also note that the PR went to staging yesterday; the next release that will bring it to app.wire.com is still a few days off (not scheduled, in fact, but very likely due this month).

btw i really appreciate your patience and helpful attitude.  it's great working with you!  :-)

**Comment by maximbaz** [comment]
Thanks for the kind words, happy to collaborate with you too 🙂 I have some preliminary implementation, please ping me when the code reaches app.wire.com so I can do some final testing before submitting a PR.

**Comment by fisx** [comment]
@maximbaz *now* this ticket is legitimately closed, and https://github.com/wireapp/wire-server/pull/561 is in production.

please re-open (or ping me) if you need anything else from the backend.
