### ISSUE TITLE
demo mode not runnable unless all services compiled natively (not with Docker)? 

### ISSUE THREAD

**Issue by romanrev** [wireapp/wire-server#564]
I've built all services with Docker (changing directories to each of the `services` subdirs and running `make docker` or `make build-docker` there, and then tried to follow the [demo mode documentation](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md) in order to run the Wire server locally in demo mode. `deploy/docker-ephemeral/run.sh` succeeded, however the `deploy/services-demo/demo.sh` produced an error
```
zauth is not compiled. How about you run 'cd /Users/roman/wire-server && make services' first?
```
Looking at the `deploy/services-demo/demo.sh`  I can see it checks for all services to be present in `dist/` which means one needs to install all the dependencies and tools locally and build with `make services` to make the demo run work?

**Comment by jschaul** [comment]
> demo mode not runnable unless all services compiled natively (not with Docker)?

Correct - the current demo mode that is part of this repo assumes you build all services natively. (there is also a docker-based demo deployment on kubernetes, [instructions here](https://github.com/wireapp/wire-server-deploy) - if you wanted to deploy this on your local machine, you would need minikube or similar)

It would be relatively straightforward to create a second docker-compose file that starts all the docker containers in demo mode on localhost. Would you be interested in contributing a PR for this?

**Comment by romanrev** [comment]
yes, I will have a go at it

**Comment by neongreen** [comment]
Add to your ~/.stack/config.yaml:

```haskell
extra-include-dirs:
- /usr/local/opt/openssl/include
- /usr/local/opt/icu4c/include

extra-lib-dirs:
- /usr/local/opt/openssl/lib
- /usr/local/opt/icu4c/lib
```

**Comment by romanrev** [comment]
thanks @neongreen, that solved this one. However I got the next issue:
```
--  While building package cryptobox-haskell-0.1.1 using:
      /Users/roman/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.2.0.1 configure --with-ghc=/Users/roman/.stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc --with-ghc-pkg=/Users/roman/.stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/roman/.stack/snapshots/x86_64-osx/lts-12.10/8.4.3/pkgdb --package-db=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/pkgdb --libdir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/lib --bindir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/bin --datadir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/share --libexecdir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/libexec --sysconfdir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/etc --docdir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/doc/cryptobox-haskell-0.1.1 --htmldir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/doc/cryptobox-haskell-0.1.1 --haddockdir=/Users/roman/Wire/wire-server/.stack-work/install/x86_64-osx/lts-12.10/8.4.3/doc/cryptobox-haskell-0.1.1 --dependency=base=base-4.11.1.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=hashable=hashable-1.2.7.0-8MkquYouWwiLIw3HmVGSkN --dependency=unordered-containers=unordered-containers-0.2.9.0-IkfpzvG0LzrHAbTzfMidvY --extra-include-dirs=/usr/local/opt/icu4c/include --extra-include-dirs=/usr/local/opt/openssl/include --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-lib-dirs=/usr/local/opt/openssl/lib --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/roman/Wire/wire-server/.stack-work/logs/cryptobox-haskell-0.1.1.log

    Configuring cryptobox-haskell-0.1.1...
    clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
    Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: Missing dependency on a foreign
    library:
    * Missing (or bad) C library: cryptobox
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
    library file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
make: *** [install] Error 1
```

**Comment by romanrev** [comment]
thank you @jschaul, I've used the prebuilt docker image in the `demo.sh` script for invoking `zauth` for now.
I have another question, this time related to the inter-dependency of the services: I've noticed that brig config file [has references to `galley`](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/conf/brig.demo.yaml#L19-L22), while the `galley` is [referencing `brig`](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/conf/galley.demo.yaml#L11-L13) and [`spar`](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/conf/galley.demo.yaml#L19-L21), while `spar` [back-references both of them](https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/conf/spar.demo.yaml#L17-L23). Could you tell if that is what happening in reality (and then I will need to split my custom `docker-compose.yaml` into 3, and launch them separately) or one can remove references from some of the mentioned config files?

**Comment by neongreen** [comment]
To handle certain API requests, Brig might have to consult Galley. Same for Galley and Spar, or Spar and Brig.

However, if you just run all of them together (in any order), circular dependencies shouldn't prevent the services from starting – otherwise `demo.sh` wouldn't work at all. The only requirement is that all services are running when you start making API requests.

Can you say why exactly you would need to split the `docker-compose.yaml` file into 3?

**Comment by romanrev** [comment]
@neongreen the reason is I am linking containers in `docker-compose.yaml` and circular dependencies are an issue in that case:
```
$ ./deploy/services-demo/demo.sh docker
re-using existing TURN secret
re-using existing public/private keys
Connection to 127.0.0.1 port 9042 [tcp/*] succeeded!
Connection to 127.0.0.1 port 9200 [tcp/wap-wsp] succeeded!
Connection to 127.0.0.1 port 6379 [tcp/*] succeeded!
ERROR: Circular dependency between brig and galley and spar
pkill: signalling pid 127: Operation not permitted
pkill: signalling pid 6051: Operation not permitted
```

**Comment by neongreen** [comment]
Oh, I see.

I think that a cleaner solution would be to use aliases (https://medium.com/@yani/two-way-link-with-docker-compose-8e774887be41), but it would require modifying `*.demo.yaml` files.

Ideally we should have a way to override YAML config vars, but... yeah.

**Comment by romanrev** [comment]
ah, nice, thank you! I've updated both `docker-compose.yaml` to use `networks` instead - I need that anyway because there is no other way to link services deployed by an external docker-compose (from `run.sh` script). Still getting some errors and one of them seems to be related to the nginx not having `libgcc` in its container?:
```
nginz_1      | Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/lib/libzauth.so)
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_FindEnclosingFunction: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_Backtrace: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_GetRegionStart: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_GetTextRelBase: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_RaiseException: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_GetIPInfo: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_GetLanguageSpecificData: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_GetDataRelBase: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_SetGR: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_DeleteException: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_Resume: symbol not found
nginz_1      | Error relocating /usr/lib/libzauth.so: _Unwind_SetIP: symbol not found
services-demo_nginz_1 exited with code 127
```

**Comment by romanrev** [comment]
@jschaul @neongreen after I have successfully launched the Wire server locally using the changes from PR #571 I am able to generate user/password and login using Swagger UI, however when I am trying to run the latest [wire-desktop](https://github.com/wireapp/wire-desktop/) against the localhost (`yarn start:localhost`) I am seeing that the app is trying to open hit the URL `http://localhost:8081` and getting authorisation required: 
```
wire-desktop::ElectronWrapperInit [2019-01-19 13:55:11] Navigating inside webview. URL: http://localhost:8081/?hl=en&id=ec30c0f4-3b0c-4ef5-a73a-8d32c3ad9abd
[47775:0119/135512.122914:INFO:CONSOLE(170)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: /Users/roman/Wire/wire-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js (170)
```

**Comment by tiago-loureiro** [comment]
@romanrev questions regarding our wire-desktop version are probably better answered by our colleagues @bennyn @atomrc @ffflorian @Yserz

**Comment by jschaul** [comment]
@romanrev Have you seen [this wiki page](https://github.com/wireapp/wire-webapp/wiki/Self-hosting) ? (Perhaps [our current kubernetes-based deployment](https://github.com/wireapp/wire-server-deploy/blob/master/charts/webapp/templates/deployment.yaml#L29-L56) will also be useful). You probably need to set a few environment variables.

**Comment by julialongtin** [comment]
Closing this issue, as it looks like @romanrev has it all figured out.
