### ISSUE TITLE
How connect a wire-webapp client to a wire-server with "fake" AWS dependencies in demo mode with docker

### ISSUE THREAD

**Issue by gabek001** [wireapp/wire-server#616]
I have setup a wire-server in demo mode with docker.
I have clone wire-webapp repo and setup a computer to run it, it open me a browser with a login/password.
I found nowhere how connect my wire-webapp client to my wire-server in demo mode. I tried modified the .env but i never was successfully. Could you give me some help on how do it ?

**Comment by tiago-loureiro** [comment]
Hi @gabek001 

Please refer to https://github.com/wireapp/wire-webapp/wiki/Self-hosting in order to figure out how to configure the webapp to point to a custom backend.
