### ISSUE TITLE
why not use zeromq 

### ISSUE THREAD

**Issue by ericfjl** [wireapp/wire-server#643]
there are so many node in wire service ：like brig 、galley、cannon、cargohold、restund and so on，use zeromq（zmq） can quickly and simpley to tranfer data

**Comment by fisx** [comment]
Thanks for your interest in wire!  :-)

I doubt zeromq will float to the top of our priority list any time soon; the internal rest APIs we use are not perfect, but more than adequate in terms of performance, stability, and maintainability.  Also, we tend to favour pure Haskell solutions over bindings into C++ code.

If you want to implement this, please re-open this issue and make a strong case for the benefits, then we can discuss it further.
