### ISSUE TITLE
System.Logger does not export "simpleSettings"

### ISSUE THREAD

**Issue by mikroice90** [wireapp/wire-server#678]
Hi,

when i try to do **make** on wire-server cloned repository i get this error.

![logger error](https://user-images.githubusercontent.com/48946750/54987450-e9661600-4fb4-11e9-8eaf-5593a02a6ea2.JPG)

How to fix it?
It looks like whis method did not exist in included libraries.
Thaks in advice for help.

**Comment by fisx** [comment]
We are currently running on [this branch of tinylog](https://github.com/wireapp/wire-server/issues/678).  stack should have picked this up from the entry in `stack.yaml`.  Which wire-server commit are you on?

**Comment by mikroice90** [comment]
The newest one (I think). I cloned it at friday.

**Comment by ChrisPenner** [comment]
These errors further imply that somehow it's building against a non-forked version of `tinylog` (we added new' and simpleSettings);

Please double check that you see this in your stack.yaml:
```
- git: https://gitlab.com/fisx/tinylog
  commit: fd7155aaf6f090f48004a8f7857ce9d3cb4f9417
```

And also please try upgrading stack to latest (1.9.3) using `stack upgrade`; it's possible your version of stack doesn't understand the (relatively new) `git` extra-deps specification 😄

**Comment by mikroice90** [comment]
I have both. Look at this please

![extra-deps](https://user-images.githubusercontent.com/48946750/55058752-36a5be80-506d-11e9-9f0f-1604fa3f1197.JPG)

and stack version

![stack_version](https://user-images.githubusercontent.com/48946750/55058765-3dcccc80-506d-11e9-9c7f-bcd9e0105bda.JPG)

Any other ideas, why this didn't work?

**Comment by fisx** [comment]
Could you do a `stack clean --full` and try again?  Can you see a `git clone` with the above commit hash in the output?

**Comment by mikroice90** [comment]
When i made `stack clean --full` I've got this

![image](https://user-images.githubusercontent.com/48946750/55060110-0102d480-5071-11e9-9e19-7dfa9cf38bca.png)

earlier I bypass it by "by hand" cloning link adding .git extention at the end ot the rspository

**Comment by fisx** [comment]
Ok, that would have been relevant enough to be added to this issue in the beginning.  :-)

What would you like us to do about your network failing?

You may be able to pull it of with your work-around, but you need to pull the right commit.  Until something changes on that branch (unlikely until we bumped the dependency to the next tinylog release and this all becomes irrelevant), you can do this:

```
$ git clone https://gitlab.com/fisx/tinylog -b settings-auxiliaries <your target path>
```

**Comment by mikroice90** [comment]
Still it looks like this

![image](https://user-images.githubusercontent.com/48946750/55061807-e7fc2280-5074-11e9-858f-b1730620e8a5.png)

I have no problem with internet connection.

**Comment by fisx** [comment]
I would call "the remote end hung up unexpectedly" a network issue, and it's certainly not something we can help you with.

It looks like you are downloading the right commit now, but I'm not sure it's to the right location.  If manually injecting this dependency into your .stack-work doesn't work, you will need to find out why you can't download it the usual way.

Also in the future, could you paste text rather than images pls?  It works much better if I want to cut&paste something in order to understand your issue.

**Comment by mikroice90** [comment]
Ok, after adding `.git` after tunylog and then running command that You propose me earlier. It's finally work.

Thanks for help and for the patience

**Comment by fisx** [comment]
Interesting, I wouldn't have expected the suffix makes any difference.

Glad you figured it out!  :-)
