### ISSUE TITLE
Will there be instructions?

### ISSUE THREAD

**Issue by NexFive** [wireapp/wire-server#70]
Hello! Will there be installation instructions for the wire server on ubuntu?

**Comment by FihlaTV** [comment]
I tried by installing  Haskell, Stack and ghc, but when I run stack build I am stuck in lib/ types-common-journal in ubuntu

**Comment by tiago-loureiro** [comment]
Thanks for your interested in the wire-server!

We are currently in the process of making such documentation available but it's still a work in progress.

You can have a look at https://github.com/wireapp/wire-server/tree/develop/build/alpine where you can find out how to create docker images for all the services.

In case you want to venture a bit and use `stack` (we are using version 1.5.1), you can also run `stack install` on the top-level folder.

However, there are a few other dependencies such as `rust` and `cargo` (for building [cryptobox-c](https://github.com/wireapp/cryptobox-c)) as well as openssl, icu and others. You can have a look at our [image builder](https://github.com/wireapp/wire-server/blob/develop/build/alpine/Dockerfile.builder) to see what we use to build all our services.

Note that this is purely to build the services. Documentation on how to run them (which requires setting up some AWS services among others) is something that is still being worked on.

**Comment by incubus8** [comment]
@tiago-loureiro is there any working docker compose setup other than just Dockerfile?

**Comment by NexFive** [comment]
не понял вас


2017-09-23 22:31 GMT+03:00 ☁ Rheza Satria <notifications@github.com>:

**Comment by NexFive** [comment]
there are people who can install wire on my server?

2017-09-23 23:56 GMT+03:00 Анатолий Горбань <anatolygorban3@gmail.com>:

**Comment by dnkls** [comment]
try install in Debian 

`* Missing C library: snappy
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.     `

**Comment by marcotuna** [comment]
Any updates regarding this subject? Manual instructions for installation without Docker?

**Comment by papmodern** [comment]
Wish we could even take a look at in-progress docs :D

**Comment by tiago-loureiro** [comment]
To all those interested in building wire-server, here are our updated docs on how to proceed:

 * [Natively](https://github.com/wireapp/wire-server/blob/develop/README.md#1-compile-sources-natively)
 * [Using docker](https://github.com/wireapp/wire-server/blob/develop/README.md#2-use-docker)

Will close down this issue for now. Feel free to open specific issues on steps you might need help in.
