### ISSUE TITLE
spar end-points should respond with json body in case of error.

### ISSUE THREAD

**Issue by fisx** [wireapp/wire-server#703]
The body of all spar errors should contain the usual error information, like:

```
{
  "code": 0,
  "message": "string",
  "label": "string"
}
```

End-points to check:

- [x] `delete /identity-providers/{id}`
- [x] `get /identity-providers/{id}`
- [x] `get /identity-providers`
- [x] `put /identity-providers`
- [x] `post /identity-providers`
- [x] `delete /scim/auth-tokens`
- [x] `get /scim/auth-tokens`
- [x] `post /scim/auth-tokens`

Other things to check:

- [ ] https://github.com/wireapp/wire-server/blob/87ca01cd318243ab66f6f762358c9be43e283ebc/services/spar/test-integration/Test/Spar/APISpec.hs#L609
- [ ] https://github.com/wireapp/wire-server/blob/87ca01cd318243ab66f6f762358c9be43e283ebc/services/spar/test-integration/Test/Spar/APISpec.hs#L670

Related: #700

**Comment by fisx** [comment]
ping @Yserz

**Comment by ChrisPenner** [comment]
@fisx This can probably be done generically in the error-catching middleware right? Just thinking we should try to make this as consistent as possible, so middleware would be a good place if it's possible 👍

**Comment by fisx** [comment]
> @fisx This can probably be done generically in the error-catching middleware right? Just thinking we should try to make this as consistent as possible, so middleware would be a good place if it's possible +1

Not sure a middleware works here.  The `Error` type isn't available in the middleware any more, but I'd like to cosntruct the body from that, somewhere in `Spar.Error`.  I'm open to discussing this further, but my current view is that all user errors and those 5xx errors where it's possible should be handled there where we have all the types, not in a middleware.

What I'm uncertain about is how the content-type of exceptions is determined by servant.  Need to read up on that when I get to it.

**Comment by fisx** [comment]
@Yserz I get json errors when I try this:

```
$ curl --header "Authorization: Bearer $BEARER" https://$SERVER/identity-providers/4ac4c7d3-a646-4f7c-a421-f1350d2f2c42
{"code":404,"message":"Could not find IdP.","label":"not-found"}
```

It's probably just *some* errors that have this problem.  Can you help me reproduce this?

**Comment by fisx** [comment]
ah, as discussed off-line:

```
$ curl -X POST --header 'Content-Type: application/xml' --header 'Accept: application/json;charset=utf-8' --header "Authorization: Bearer $BEARER" -d '$IDP_METADATA' https://$SERVER/identity-providers
"1:1 (0)-1:14 (13): Found content after root element: EventContent (ContentText \"$IDP_METADATA\")"

```

thanks!
