### ISSUE TITLE
How can we setup production wire server?

### ISSUE THREAD

**Issue by techindustan** [wireapp/wire-server#705]
Are there any steps to set up wire server with production architecture? We want to set up wire on our servers and don't call wire stuff. Is there a way?

**Comment by fisx** [comment]
Please read [the documentation](https://github.com/wireapp/wire-server#how-to-install-and-run-wire-server).

It's certainly not as polished as it could be, so feel free to open a new issue if you have any specific questions that are not answered there.

Thanks and enjoy!
