### ISSUE TITLE
Error while nginz make command

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#716]
I am getting an error during
`make -C services/nginz`
Error:
```
make: Entering directory '/var/www/html/wire-server/services/nginz'
#Find keys on https://nginx.org/en/pgp_keys.html
gpg --verify nginx-1.14.2.tar.gz.asc nginx-1.14.2.tar.gz
gpg: Signature made Tue 04 Dec 2018 02:54:14 PM UTC
gpg:                using RSA key <THE RSA KEY>
gpg: Can't check signature: No public key
Makefile:113: recipe for target 'src' failed
make: *** [src] Error 2
make: Leaving directory '/var/www/html/wire-server/services/nginz'
```
I used one of the keys from https://nginx.org/en/pgp_keys.html, as suggested above and imported it using:
`gpg --import ../key/nginx_signing.key `

But I am still getting the same error.

I also tried gpg --recv-keys:
`gpg --recv-keys <THE RSA KEY>`

The error is still same.

**Comment by tiago-loureiro** [comment]
Have you tried importing _all the keys_ available at https://nginx.org/en/pgp_keys.html?

**Comment by R4m4n** [comment]
No I didn't, now I did, thanks that worked. 👍
