### ISSUE TITLE
Error while signing up using twilio API.

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#732]
When I try to create an account using my phone number I'm getting this error in the console:

`SMS failed., error=MessageErrorResponse {erStatus = MessageOther, erErrorText = Just "Bad Credentials"}, phone=<phone>`

and
`ErrorResponse {errStatus = 400, errMessage = "The 'From' number <insert-sender-number-here> is not a valid phone number, shortcode, or alphanumeric sender ID.", errCode = Just 21212, errMoreInfo = Just "https://www.twilio.com/docs/errors/21212"}`

Twilio sid and token have been set up, but I'm not able to figure out where to add the "from" in the Twilio configurations.

**Comment by jschaul** [comment]
It's in the brig.yaml configuration. See `smsSender`. Feel free to make a PR to improve documentation around this.

**Comment by R4m4n** [comment]
Alright, Thanks @jschaul. Twilio is now working fine.

I have requested the merge pull request.
