### ISSUE TITLE
Getting Error:  "Empty TURN list" while trying to use audio and video call.

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#744]
When trying to connect using audio and video calls, I'm getting:

`[brig] E, request=d88126e2b7144b04d4773111f037b578, Empty TURN list, check turn file! CallStack (from HasCallStack):   error, called at src/Brig/App.hs:257:31 in brig-1.35.0-Fg0EoeQZ8mD7xkabAFGd0V:Brig.App`

`[brig] D, code=500, label=server-error, request=d88126e2b7144b04d4773111f037b578, "Server Error"`

I've set up the TURN using restund on 3478 port.

**Comment by tiago-loureiro** [comment]
The issue is not about the turn server itself but about advertising it. Brig expects a list of TURN urls, just like you see in this example: https://github.com/wireapp/wire-server/tree/develop/deploy/services-demo/resources/turn

**Comment by R4m4n** [comment]
These files exist in the server that I deployed on my server. Am I supposed to make changes to these files? 
Or add more?

**Comment by tiago-loureiro** [comment]
Difficult to say what can be wrong without more info; potentially if u show the config of the TURN servers and the url on the config file.

**Comment by R4m4n** [comment]
I've followed this:
https://nil.uniza.sk/installing-and-configuring-restund-stunturn-server/

and user 127.0.0.1 as the Ip as I'm setting up the TURN on the same server. Am I supposed to use a different IP or set it up on a different server?

**Comment by R4m4n** [comment]
@tiago-loureiro Anything I should try or missing here?

**Comment by tiago-loureiro** [comment]
Can you please share:
 * brig's log
 * content of of your turn-servers.txt (or similar file pointed to from brig's config)
 * content of the turn config server

**Comment by jschaul** [comment]
Your TURN server needs to have a public IP (reachable from anywhere in the internet). This needs to be in the configuration file for the TURN server itself. Brig's configuration must use that same (public) IP. Using 127.0.0.1 will not work.

**Comment by R4m4n** [comment]
@jschaul 
If I try to run it on public IP I get this error: 
`udp listen x.x.x.x:3478: Cannot assign requested address.`

**Comment by R4m4n** [comment]
@tiago-loureiro 

brig's log shown no error and nothing related to the call:

```
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#21
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#22
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#23
[brig] I, request=2e6d27929cd18ac47f1e9fbfc10eb0ff, user=d37cacfd-32e5-4bc3-a1c6-b70085d9354b, client=14429c4835233972, last resort prekey used
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#25
[brig] I, request=aac2ec860b669efb498d98925cd1288b, user=15369cc8-eabd-4584-880f-792438a46fff, client=e172e7dd729f54f4, last resort prekey used
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#26
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#27
[brig] D, logger=cassandra.brig, Connection established: datacenter1:rack1:127.0.0.1:9042#28
[brig] I, request=aac2ec860b669efb498d98925cd1288b, user=15369cc8-eabd-4584-880f-792438a46fff, client=810eb59da59f1b01, last resort prekey used
[brig] I, request=aac2ec860b669efb498d98925cd1288b, user=15369cc8-eabd-4584-880f-792438a46fff, client=77641346713204ff, last resort prekey used
[brig] I, request=aac2ec860b669efb498d98925cd1288b, user=15369cc8-eabd-4584-880f-792438a46fff, client=4ecc2020e66342e7, last resort prekey used
[brig] D, logger=cassandra.brig, Reaping idle connection: datacenter1:rack1:127.0.0.1:9042#20
[brig] D, logger=cassandra.brig, Connection closed: datacenter1:rack1:127.0.0.1:9042#20
[brig] D, logger=cassandra.brig, Reaping idle connection: datacenter1:rack1:127.0.0.1:9042#22
```
content of of your turn-servers.txt:

`turn:127.0.0.1:3478`

content of the turn config server:
```
#
# restund.conf
#

# core
daemon			yes
debug			no
realm			myrealm
syncinterval		600
#udp_listen		127.0.0.1:3478
udp_listen		127.0.0.1:3478
#udp_listen		1.2.3.4:3478
udp_sockbuf_size	524288
#tcp_listen		127.0.0.1:3478
tcp_listen		127.0.0.1:3478
#tcp_listen		1.2.3.4:3478
#tls_listen     1.2.3.4:3479,/path/to/keyandcert.pem
udp_internal_listen 4.5.6.7

# modules
module_path		/usr/local/lib/restund/modules
module			stat.so
module			binding.so
#module			auth.so
module			turn.so
#module			mysql_ser.so
module			syslog.so
module			status.so

# auth
auth_nonce_expiry	3600

# turn
turn_max_allocations	512
turn_max_lifetime	600
turn_relay_addr		127.0.0.1
turn_relay_addr6	::1

# mysql
mysql_host		localhost
mysql_user		ser
mysql_pass		heslo
mysql_db		ser
mysql_ser		0

# syslog
syslog_facility		24

# status
#status_udp_addr		127.0.0.1
#status_udp_port		33000
#status_http_addr	127.0.0.1
status_http_addr	127.0.0.1
status_http_port	8089
```

**Comment by R4m4n** [comment]
It's working now, the issue was with the private IPs that I was using.

**Comment by jschaul** [comment]
Good to hear you managed to solve your issue!

We understand our documentation is perhaps not clear enough on some points. Would you be willing to make a PR to improve documentation on the points that were not clear for you? Possibly you could make changes to this file: https://github.com/wireapp/wire-server/tree/develop/services/restund/README.md
Thanks!

**Comment by R4m4n** [comment]
@jschaul Yeah Sure!
