### ISSUE TITLE
Is there an admin panel for the Wire?

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#786]
Is there any admin panel from where I can manage payments, settings and supervise users, etc.?

**Comment by techindustan** [comment]
@tiago-loureiro Can you please help on this? Do we have a superadmin sort of thing built in Wire to manage payments, subscriptions, team licenses, etc.?

**Comment by jschaul** [comment]
@techindustan @R4m4n please have a look at the enterprise section here: https://wire.com/en/pricing/

**Comment by tiago-loureiro** [comment]
Please get in touch with us through the correct channel as mentioned by @jschaul if you are interested in such feature(s)
