### ISSUE TITLE
any mirror for setup wire server Documentation ?

### ISSUE THREAD

**Issue by Nemra1** [wireapp/wire-server#79]
i need to start setup wire server but the website Documentation is down 
https://medium.com/@wireapp/

**Comment by tiago-loureiro** [comment]
Hi @Nemra1,
The location that you have mentioned is up but relates only to announcements.
For some documentation and instructions on how to build wire server, please have a look at:
https://github.com/wireapp/wire-server/blob/develop/README.md
and
https://github.com/wireapp/wire-server/blob/develop/build/alpine/README.md
