### ISSUE TITLE
ETA on instructions?

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [wireapp/wire-server#80]
First off GREAT work. Will there be an ETA on when we can expect the full instructions/documentation. Curious and excited to setup a standalone server and clients.

**Comment by tiago-loureiro** [comment]
Hi @imanodaysoffdotcom, thank you for your interest!

We don't have an exact ETA for the instructions/documentation but some of it has been discussed in [this issue](https://github.com/wireapp/wire-server/issues/70). We will use that issue to track our progress with the instructions and documentation.
