### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by chazanov** [wireapp/wire-server#810]
I'm getting a test failure when building

```
Test suite failure for package types-common-0.16.0
    tests:  exited with: ExitFailure 1
Logs printed to console


<stderr>: commitAndReleaseBuffer: invalid argument (invalid character)
Progress 389/396
```

https://github.com/wireapp/wire-server/issues/764 states it has been fixed, but that's not correct.

**Comment by fisx** [comment]
duplicate of #764 (sorry for the delay in responding!)
