### ISSUE TITLE
Makefile glitch

### ISSUE THREAD

**Issue by fisx** [wireapp/wire-server#821]
if you do

```
make -C services/galley/ integration
```

it will write to `services/galley/dist`, but it should write to `dist`.  Somewhere we probably need to make the path relative to the repo root, not to the working directory.

**Comment by mheinzel** [comment]
Is this fixed by https://github.com/wireapp/wire-server/pull/904?

**Comment by fisx** [comment]
> Is this fixed by #904?

yes, thanks!
