### ISSUE TITLE
Getting error: " /onboarding/v3 " out of no-where.

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#859]
`[error] 17710#0: *1 open() "/var/www/html/wire-server/deploy/services-demo/html/onboarding/v3" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /onboarding/v3 HTTP/1.1", host: "<example.com>"`

I'm getting this error out of no-where. It occurs suddenly sometimes but is working fine most of the time.
But when this issue occurs, there's a popup in the iOS device showing the error again and again.

And there's no directory `/onboarding/v3`.

**Comment by jschaul** [comment]
Similar to #860 , the route is missing from the nginx configuration. Here, it's a `with_zauth` that is needed, it also points to `brig`.

**Comment by R4m4n** [comment]
Thank you @jschaul.
