### ISSUE TITLE
makedeb

### ISSUE THREAD

**Issue by coderzstas** [wireapp/wire-server#873]
* [x] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**

getting this error when trying to make makedeb

```
stack install . --pedantic --test --bench --no-run-benchmarks --local-bin-path=dist
Copying from /root/wire-server/.stack-work/install/x86_64-linux/a0b80d0b05ab0b136df7fe0fd432aa19c7e4d31df2e44236e5b435266ade9471/8.4.3/bin/makedeb to /root/wire-server/tools/makedeb/dist/makedeb

Copied executables to /root/wire-server/tools/makedeb/dist:
- makedeb

Warning: Installation path /root/wire-server/tools/makedeb/dist
         not found on the PATH environment variable.
cp -R -L deb /tmp/makedeb.VqSSxE4tbp
cp: cannot stat 'deb/usr/local/bin/makedeb': No such file or directory
```

ubuntu 18

**Comment by tiago-loureiro** [comment]
Hello @coderzstas 

Can you make sure to add `/root/wire-server/tools/makedeb/dist` to your PATH? Or copy the `makedeb` executable to a place in your path (assuming something like `/usr/local/bin`)

**Comment by coderzstas** [comment]
> Hello @coderzstas
> 
> Can you make sure to add `/root/wire-server/tools/makedeb/dist` to your PATH? Or copy the `makedeb` executable to a place in your path (assuming something like `/usr/local/bin`)

ok , that fixed ) thanks
now getting another error durring make step

`--  While building package brig-1.35.0 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.2.0.1 build lib:brig exe:brig exe:brig-index exe:brig-integration exe:brig-schema --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Makefile:14: recipe for target 'install' failed`
