### ISSUE TITLE
Galley Error

### ISSUE THREAD

**Issue by coderzstas** [wireapp/wire-server#874]
* [x] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**
Getting this error when trying to run  **deploy/services-demo/demo.sh**

> galley: user error (AesonException "Error in $.settings: When parsing the record Settings of type Galley.Options.Settings the key featureFlags was not present.")
> [cargohold] I, Listening on 127.0.0.1:8084
> Killed

**Comment by fisx** [comment]
it means that you need to add the feature flags config.  :)

[example](https://github.com/wireapp/wire-server/blob/develop/services/galley/galley.integration.yaml#L29-L31)

(please re-open if this wasn't helpful.)
