### ISSUE TITLE
galley: user error 

### ISSUE THREAD

**Issue by jzallimi** [wireapp/wire-server#882]
* [ ] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**
when i run demo.sh
galley: user error (AesonException "Error in $.settings: When parsing the record Settings of type Galley.Options.Settings the key featureFlags was not present.")

brig: user error (AesonException "Error in $.zauth.authSettings: key \"legalHoldAccessTokenTimeout\" not present")1

**Comment by coderzstas** [comment]
Add this to galley config

featureFlags:  # see #RefConfigOptions in `/docs/reference`
    sso: disabled-by-default
    legalhold: disabled-by-default

Also need add missing configuration to brig

**Comment by fisx** [comment]
thanks @coderzstas !

see also: https://github.com/wireapp/wire-server/issues/874

**Comment by jzallimi** [comment]
this is my file config

galley:
  host: 127.0.0.1
  port: 8085

cassandra:
  endpoint:
    host: 127.0.0.1
    port: 9042
  keyspace: galley_test

brig:
  host: 0.0.0.0
  port: 8082

gundeck:
  host: 127.0.0.1
  port: 8086

spar:
  host: 127.0.0.1
  port: 8088

settings:
  httpPoolSize: 128
  maxTeamSize: 32
  maxConvSize: 16
  intraListing: false
  conversationCodeURI: https://app.wire.com/join/

featureFlags:  # see #RefConfigOptions in `/docs/reference`
    sso: disabled-by-default
    legalhold: disabled-by-default

logLevel: Info
logNetStrings: false

journal: # if set, journals; if not set, disables journaling
  queueName: integration-team-events.fifo
  endpoint: http://localhost:4568 # https://sqs.eu-west-1.amazonaws.com
  region: eu-west-1


So im new in this things.

Thank you

**Comment by jzallimi** [comment]
when i try from web

401 Authorization Required

**Comment by fisx** [comment]
not sure if you still have a problem, and if you think it's related to the original one?  feel free to re-open, or open a new issue if that's the case.

**Comment by jzallimi** [comment]
yes i have the same problem.

**Comment by fisx** [comment]
Look at the link I posted in the duplicate issue: https://github.com/wireapp/wire-server/blob/develop/services/galley/galley.integration.yaml#L29-L31

`featureFlags` needs to be part of `settings`.

**Comment by jzallimi** [comment]
Yes featureFlags is part of settings, lilke in the post. I have the same problem

**Comment by jzallimi** [comment]
Thank you.
My only error now is: when i try to open the page  401 Authorization Required.

**Comment by coderzstas** [comment]
I have pretty same error when i trying enter to.swagger , ignore it :) i bringed webapp and android app, and it working

**Comment by jzallimi** [comment]
> I have pretty same error when i trying enter to.swagger , ignore it :) i bringed webapp and android app, and it working

So i need help again,  is there any administration website for wire-server ?

**Comment by fisx** [comment]
Have you read https://docs.wire.com/, https://github.com/wireapp/wire-server#wire-server, https://github.com/wireapp/wire-server-deploy#introduction?

**Comment by jzallimi** [comment]
if u can help me way i cant open the wire api from web:  Authorization Required 401 
thank you

**Comment by mimikadze** [comment]
Cheers,
trying to set up wire in demo mode and got an error
```
$ deploy/services-demo/demo.sh docker
re-using existing TURN secret
re-using existing public/private keys
make: Entering directory '/home/staging/wire-server/services/nginz'
make: 'zwagger-ui/swagger-ui' is up to date.
make: Leaving directory '/home/staging/wire-server/services/nginz'
Starting servicesdemo_gundeck_1 ...
Starting servicesdemo_spar_1 ...
Starting servicesdemo_gundeck_1
Starting servicesdemo_cannon_1 ...
Starting servicesdemo_spar_1
Starting servicesdemo_cannon_1
Starting servicesdemo_galley_1 ...
Starting servicesdemo_proxy_1 ...
Starting servicesdemo_galley_1
Starting servicesdemo_proxy_1
Starting servicesdemo_cargohold_1 ...
Starting servicesdemo_galley_1 ... done
Starting servicesdemo_brig_1 ...
Starting servicesdemo_brig_1 ... done
Starting servicesdemo_nginz_1 ...
Starting servicesdemo_nginz_1 ... done
Attaching to servicesdemo_gundeck_1, servicesdemo_spar_1, servicesdemo_cannon_1, servicesdemo_cargohold_1, servicesdemo_proxy_1, servicesdemo_galley_1, servicesdemo_brig_1, servicesdemo_nginz_1
gundeck_1    | I, logger=cassandra.gundeck, Known hosts: [datacenter1:rack1:172.18.0.8:9042]
gundeck_1    | I, logger=cassandra.gundeck, New control connection: datacenter1:rack1:172.18.0.8:9042#<socket: 11>
spar_1       | D, logger=cassandra.spar, Connecting to 172.18.0.8:9042
gundeck_1    | I, Listening on gundeck:8086
spar_1       | I, logger=cassandra.spar, Known hosts: [datacenter1:rack1:172.18.0.8:9042]
spar_1       | I, logger=cassandra.spar, New control connection: datacenter1:rack1:172.18.0.8:9042#<socket: 11>
spar_1       | D, logger=cassandra.spar, Connection established: datacenter1:rack1:172.18.0.8:9042#<socket: 12>
spar_1       | I, Listening on spar:8088
cannon_1     | I, Listening on cannon:8083
cargohold_1  | I, Listening on cargohold:8084
proxy_1      | I, Listening on 127.0.0.1:8087
galley_1     | galley: user error (AesonException "Error in $.settings: When parsing the record Settings of type Galley.Options.Settings the key featureFlags was not present.")
servicesdemo_galley_1 exited with code 1
brig_1       | brig: user error (AesonException "Error in $.zauth.authSettings: key \"legalHoldUserTokenTimeout\" not found")
nginz_1      | 2020/04/30 09:06:17 [emerg] 1#0: host not found in upstream "galley:8085" in /configs/conf/nginz/upstreams-docker:19
nginz_1      | nginx: [emerg] host not found in upstream "galley:8085" in /configs/conf/nginz/upstreams-docker:19
servicesdemo_brig_1 exited with code 1
servicesdemo_nginz_1 exited with code 1
```

While feature flags looks to be enabled in `services/galley/galley.integration.yaml`
```
settings:
  httpPoolSize: 128
  maxTeamSize: 32
  maxFanoutSize: 18
  maxConvSize: 16
  intraListing: false
  conversationCodeURI: https://app.wire.com/join/
  concurrentDeletionEvents: 1024
  deleteConvThrottleMillis: 0
  featureFlags:
    sso: disabled-by-default
    legalhold: disabled-by-default
```

Current commit version I'm using is 5a311f8456d09c3c25dc72cbe34c078cdd68121d

Any ideas?

**Comment by akshaymankar** [comment]
@mimikadze While running services-demo in docker we use [this file](https://github.com/wireapp/wire-server/blob/5a311f8456d09c3c25dc72cbe34c078cdd68121d/deploy/services-demo/conf/galley.demo-docker.yaml) as config for galley. It seems that we missed adding feature flags to this file. Can you please open a new issue for this?
