### ISSUE TITLE
cant make video and audio calls

### ISSUE THREAD

**Issue by coderzstas** [wireapp/wire-server#888]
* [x] I have seen https://docs.wire.com/ and https://github.com/wireapp/wire-server-deploy - the documentation there does not answer my question.

**My question:**
Hello again :) I configured and running wire-server , also configured restund on machine with wire-server and another vps , when i trying to make (vide)call , there is nothing hapening :(
I have added this 2 servers to turn config files .

Logs on my wire-server machine with restund is

> turn: using public address xx.xx.xx.xx
> zrest: selftest passed (pass=DHG0HBy7Ci5hWxoO2Xn32PCLHeIeVviqEk7eh34XyIzSeI/xOqX0wh45XKjsv+PLhir7D6pdw3fbUyR+J8HryQ==)
> stun server ready

Logs of restund on another vps

> turn: using public address xx.xx.xx.xx
> zrest: selftest passed (pass=XHG0XBy7Ci5hWxoO2Tn32PCLHeIeVviqEk7eh34DyIzSeI/xOqX0wh45XKjsv+PXhir7X6pxw3fbUyR+J8HryQ==)
> stun server ready
> turn: mapping to public:  xx.xx.xx.xx:35174  -->  xx.xx.xx.xx:35174
> 

Strange what i see this messages  turn: mapping to public:  xx.xx.xx.xx:35174  -->  xx.xx.xx.xx:35174 only on another vps only with restund server on in . And no logs like this on vpn with wire-server
ip changed for privacy :) thanks

**Comment by jschaul** [comment]
Have you seen https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/hosts.example.ini#L12-L16 and https://docs.wire.com/understand/restund.html ?

Make sure the config [here](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L60-L64) matches the DNS names and the port numbers that restund is listening on.

There is no need to have more than one restund server. One is enough. Make sure the restund server has a public IP address, and UDP traffic is allowed. Look at the logs from your clients, not from the restund servers (probably your clients can't reach the restund server).

**Comment by coderzstas** [comment]
> Have you seen https://github.com/wireapp/wire-server-deploy/blob/develop/ansible/hosts.example.ini#L12-L16 and https://docs.wire.com/understand/restund.html ?
> 
> Make sure the config [here](https://github.com/wireapp/wire-server-deploy/blob/develop/values/wire-server/prod-values.example.yaml#L60-L64) matches the DNS names and the port numbers that restund is listening on.
> 
> There is no need to have more than one restund server. One is enough. Make sure the restund server has a public IP address, and UDP traffic is allowed. Look at the logs from your clients, not from the restund servers (probably your clients can't reach the restund server).

Thanks , but im using this server not wire-deploy

here is bit more logs from restund

> root@kubenode01:~# restund
> udp listen: restundip:3478
> tcp listen: restundip:3478
> stat: module loaded
> drain: module loaded
> binding: module loaded
> turn: using public address restundip
> turn: lifetime=3600 ext=restundip ext6=? bsz=65536
> status: module loaded (udp=restundip:33000 http=51.75.140.6:9099)
> zrest: selftest passed (pass=EZ3MhomISb+XG+C0UrqN4Zf+63bQQjhug7NI88xBEYOF0tgTbf7/2OhDru50lmSv4EAdTKVNoY7yrRhB5OmI3A==)
> zrest: module loaded
> auth: module loaded (nonce_expiry=3600s)
> stun server ready
> binding: request from 46.150.103.97:40593
> binding: request from 46.150.103.97:43862
> turn: allocation 0x558e810f0910 created UDP/46.150.103.97:43862/restundip:3478 - restundip:36154 (600s)
> turn: mapping to public:  restundip:36154  -->  restundip36154
> turn: allocation 0x558e810f0f10 created UDP/46.150.103.97:40593/restundip:3478 - restundip:32824 (600s)
> turn: mapping to public:  restundip:32824  -->  restundip:32824
> binding: request from 46.150.103.97:40593
> turn: mapping to public:  restundip:32824  -->  restundip:32824

also changed ips for privacy . Thanks

**Comment by jschaul** [comment]
Please follow the links I posted, so you understand how `brig` and `restund` and your browser interact. We cannot provide support if you install and configure components differently to how we suggest, especially if you don't detail your setup.

**Comment by jschaul** [comment]
Please fill out these sections here: https://github.com/wireapp/wire-server/blob/add-issue-template/.github/ISSUE_TEMPLATE/question-installation.md to provide context.

**Comment by coderzstas** [comment]
> Please fill out these sections here: https://github.com/wireapp/wire-server/blob/add-issue-template/.github/ISSUE_TEMPLATE/question-installation.md to provide context.

my issue is solved , i can make calls but with very big delay :(
